In [1]:
import pandas as pd

df = pd.read_csv('timeSeries_v2.csv')
# convert data frame to timeSeries
df['date'] = pd.to_datetime(df['date'])
df.set_index('date',inplace=True)
df

,fips,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
date,,,,,,,,,,,,,,,,,,,,
2000-01-04,13293,0.667669,0.605742,-0.025995,-0.162733,0.196127,0.193740,-0.279952,-0.336161,0.060936,-0.190941,0.184897,-0.367359,1.126956,-1.246620,0.782961,0.237211,1.236782,-0.866626,3
2000-01-04,51155,0.586479,-0.415565,-0.187427,-0.573271,-0.003411,-0.007160,-0.753719,-0.909549,0.184737,-0.579757,0.157409,-0.228341,0.626952,-0.730360,0.725758,0.187646,1.054347,-0.762055,1
2000-01-04,8071,-0.400429,-2.302659,-1.324002,-1.463810,-1.949404,-1.919691,-1.106115,-1.633975,1.046487,-1.458034,0.696179,0.922422,0.475435,0.895092,0.800562,1.214339,0.079763,1.488483,0
2000-01-04,46109,-0.396821,0.374866,-1.491979,-2.477243,-2.334651,-2.309556,-2.599402,-2.337890,-1.451375,-2.338892,1.037033,1.532558,-0.001841,2.024730,0.589350,1.193097,-0.405129,1.915858,1
2000-01-04,9011,2.327552,0.770883,0.089626,-0.307000,0.412458,0.410553,-0.674200,-0.091888,-1.715969,-0.418037,1.553812,1.663853,0.687558,1.733376,1.966626,2.276435,0.963130,2.015882,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-27,28015,-0.223616,0.886321,0.360135,-0.006889,0.638667,0.593552,-0.284137,0.032113,-0.905195,-0.032662,-0.859656,-0.977495,-0.380632,-1.037049,-0.664719,-0.736377,-0.405129,-0.557461,2
2016-12-27,19079,-0.400429,0.410139,-1.190929,-1.597391,-1.358692,-1.356772,-1.489481,-1.625584,-0.087139,-1.656744,0.520254,0.879944,0.202706,1.027991,0.523347,0.888630,0.094165,1.052015,0
2016-12-27,40077,-0.400429,0.613759,-0.878971,-0.643624,-0.704759,-0.725229,-0.504280,-0.555260,-0.019170,-0.669219,-0.892642,-0.950463,-1.183668,-0.459451,-0.748323,-0.548740,-1.216483,0.442778,3
2016-12-27,40109,-0.400429,0.482288,-1.044767,-0.895646,-1.019871,-1.021607,-0.688430,-0.963624,0.514872,-0.905778,-0.364868,-0.019813,-0.380632,0.230599,-0.171891,0.824904,-0.717188,1.738543,3
2016-12-27,1019,0.203984,0.531990,0.401584,-0.103067,0.636692,0.602503,-0.325152,-0.272762,-0.230360,-0.133307,-0.925628,-1.074035,-0.342753,-1.190394,-0.620716,-0.938175,-0.069066,-1.134872,4

In [2]:
df.corr().score.sort_values()

PS            -0.106304
PRECTOT       -0.057844
fips          -0.055629
WS50M_MIN     -0.049703
WS10M_MIN     -0.031247
WS50M         -0.030570
WS50M_MAX     -0.010411
WS10M         -0.009904
WS10M_MAX      0.005758
T2MDEW         0.017985
T2MWET         0.018797
QV2M           0.021082
WS10M_RANGE    0.028687
WS50M_RANGE    0.033702
T2M_MIN        0.158055
T2M            0.182815
TS             0.188828
T2M_RANGE      0.210610
T2M_MAX        0.214523
score          1.000000
Name: score, dtype: float64

In [3]:
df_new = df[['PS','T2M_RANGE','TS','T2M_MAX','T2M','score']]
df_new

                  PS  T2M_RANGE        TS   T2M_MAX       T2M  score
date
2000-01-04  0.605742   0.060936 -0.190941 -0.279952 -0.162733      3
2000-01-04 -0.415565   0.184737 -0.579757 -0.753719 -0.573271      1
2000-01-04 -2.302659   1.046487 -1.458034 -1.106115 -1.463810      0
2000-01-04  0.374866  -1.451375 -2.338892 -2.599402 -2.477243      1
2000-01-04  0.770883  -1.715969 -0.418037 -0.674200 -0.307000      0
...              ...        ...       ...       ...       ...    ...
2016-12-27  0.886321  -0.905195 -0.032662 -0.284137 -0.006889      2
2016-12-27  0.410139  -0.087139 -1.656744 -1.489481 -1.597391      0
2016-12-27  0.613759  -0.019170 -0.669219 -0.504280 -0.643624      3
2016-12-27  0.482288   0.514872 -0.905778 -0.688430 -0.895646      3
2016-12-27  0.531990  -0.230360 -0.133307 -0.325152 -0.103067      4

[2546118 rows x 6 columns]

In [4]:
df_shift= df_new[['TS','T2M_MAX','T2M_RANGE','T2M','PS']].shift()
df_shift.columns = ['TS_pre','T2M_MAX_pre','T2M_RANGE_pre','T2M_pre','PS_pre']
df_total = pd.concat([df_new,df_shift],axis=1)
df_total

,PS,T2M_RANGE,TS,T2M_MAX,T2M,score,TS_pre,T2M_MAX_pre,T2M_RANGE_pre,T2M_pre,PS_pre
date,,,,,,,,,,,
2000-01-04,0.605742,0.060936,-0.190941,-0.279952,-0.162733,3,NaN,NaN,NaN,NaN,NaN
2000-01-04,-0.415565,0.184737,-0.579757,-0.753719,-0.573271,1,-0.190941,-0.279952,0.060936,-0.162733,0.605742
2000-01-04,-2.302659,1.046487,-1.458034,-1.106115,-1.463810,0,-0.579757,-0.753719,0.184737,-0.573271,-0.415565
2000-01-04,0.374866,-1.451375,-2.338892,-2.599402,-2.477243,1,-1.458034,-1.106115,1.046487,-1.463810,-2.302659
2000-01-04,0.770883,-1.715969,-0.418037,-0.674200,-0.307000,0,-2.338892,-2.599402,-1.451375,-2.477243,0.374866
...,...,...,...,...,...,...,...,...,...,...,...
2016-12-27,0.886321,-0.905195,-0.032662,-0.284137,-0.006889,2,-0.135888,-0.226381,-0.257062,-0.113753,0.453428
2016-12-27,0.410139,-0.087139,-1.656744,-1.489481,-1.597391,0,-0.032662,-0.284137,-0.905195,-0.006889,0.886321
2016-12-27,0.613759,-0.019170,-0.669219,-0.504280,-0.643624,3,-1.656744,-1.489481,-0.087139,-1.597391,0.410139
2016-12-27,0.482288,0.514872,-0.905778,-0.688430,-0.895646,3,-0.669219,-0.504280,-0.019170,-0.643624,0.613759
2016-12-27,0.531990,-0.230360,-0.133307,-0.325152,-0.103067,4,-0.905778,-0.688430,0.514872,-0.895646,0.482288

In [5]:
df_total.fillna(value=0,inplace=True)
df_total

,PS,T2M_RANGE,TS,T2M_MAX,T2M,score,TS_pre,T2M_MAX_pre,T2M_RANGE_pre,T2M_pre,PS_pre
date,,,,,,,,,,,
2000-01-04,0.605742,0.060936,-0.190941,-0.279952,-0.162733,3,0.000000,0.000000,0.000000,0.000000,0.000000
2000-01-04,-0.415565,0.184737,-0.579757,-0.753719,-0.573271,1,-0.190941,-0.279952,0.060936,-0.162733,0.605742
2000-01-04,-2.302659,1.046487,-1.458034,-1.106115,-1.463810,0,-0.579757,-0.753719,0.184737,-0.573271,-0.415565
2000-01-04,0.374866,-1.451375,-2.338892,-2.599402,-2.477243,1,-1.458034,-1.106115,1.046487,-1.463810,-2.302659
2000-01-04,0.770883,-1.715969,-0.418037,-0.674200,-0.307000,0,-2.338892,-2.599402,-1.451375,-2.477243,0.374866
...,...,...,...,...,...,...,...,...,...,...,...
2016-12-27,0.886321,-0.905195,-0.032662,-0.284137,-0.006889,2,-0.135888,-0.226381,-0.257062,-0.113753,0.453428
2016-12-27,0.410139,-0.087139,-1.656744,-1.489481,-1.597391,0,-0.032662,-0.284137,-0.905195,-0.006889,0.886321
2016-12-27,0.613759,-0.019170,-0.669219,-0.504280,-0.643624,3,-1.656744,-1.489481,-0.087139,-1.597391,0.410139
2016-12-27,0.482288,0.514872,-0.905778,-0.688430,-0.895646,3,-0.669219,-0.504280,-0.019170,-0.643624,0.613759
2016-12-27,0.531990,-0.230360,-0.133307,-0.325152,-0.103067,4,-0.905778,-0.688430,0.514872,-0.895646,0.482288

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_total[['TS','T2M_MAX','TS_pre','T2M_MAX_pre','T2M_RANGE','T2M_RANGE','T2M','T2M_pre','PS','PS_pre']], df_total['score'], test_size=0.2, random_state=1)

clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)

In [7]:
y_pred = clf.predict(X_test)

In [17]:
from sklearn import metrics

print(metrics.classification_report(y_test, y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.398     0.363     0.380     84739
           1      0.350     0.328     0.339     84589
           2      0.440     0.444     0.442     85005
           3      0.505     0.520     0.512     84830
           4      0.618     0.655     0.636     85095
           5      0.829     0.869     0.849     84966

    accuracy                          0.530    509224
   macro avg      0.523     0.530     0.526    509224
weighted avg      0.523     0.530     0.526    509224

In [9]:
metrics.mean_absolute_error(y_test, y_pred)

0.8693423719227688

In [10]:
import pandas as pd
df= pd.read_csv('timeSeries_v2.csv')

df['date'] = pd.to_datetime(df['date'])
df.set_index('date',inplace=True)
df

,fips,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
date,,,,,,,,,,,,,,,,,,,,
2000-01-04,13293,0.667669,0.605742,-0.025995,-0.162733,0.196127,0.193740,-0.279952,-0.336161,0.060936,-0.190941,0.184897,-0.367359,1.126956,-1.246620,0.782961,0.237211,1.236782,-0.866626,3
2000-01-04,51155,0.586479,-0.415565,-0.187427,-0.573271,-0.003411,-0.007160,-0.753719,-0.909549,0.184737,-0.579757,0.157409,-0.228341,0.626952,-0.730360,0.725758,0.187646,1.054347,-0.762055,1
2000-01-04,8071,-0.400429,-2.302659,-1.324002,-1.463810,-1.949404,-1.919691,-1.106115,-1.633975,1.046487,-1.458034,0.696179,0.922422,0.475435,0.895092,0.800562,1.214339,0.079763,1.488483,0
2000-01-04,46109,-0.396821,0.374866,-1.491979,-2.477243,-2.334651,-2.309556,-2.599402,-2.337890,-1.451375,-2.338892,1.037033,1.532558,-0.001841,2.024730,0.589350,1.193097,-0.405129,1.915858,1
2000-01-04,9011,2.327552,0.770883,0.089626,-0.307000,0.412458,0.410553,-0.674200,-0.091888,-1.715969,-0.418037,1.553812,1.663853,0.687558,1.733376,1.966626,2.276435,0.963130,2.015882,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-27,28015,-0.223616,0.886321,0.360135,-0.006889,0.638667,0.593552,-0.284137,0.032113,-0.905195,-0.032662,-0.859656,-0.977495,-0.380632,-1.037049,-0.664719,-0.736377,-0.405129,-0.557461,2
2016-12-27,19079,-0.400429,0.410139,-1.190929,-1.597391,-1.358692,-1.356772,-1.489481,-1.625584,-0.087139,-1.656744,0.520254,0.879944,0.202706,1.027991,0.523347,0.888630,0.094165,1.052015,0
2016-12-27,40077,-0.400429,0.613759,-0.878971,-0.643624,-0.704759,-0.725229,-0.504280,-0.555260,-0.019170,-0.669219,-0.892642,-0.950463,-1.183668,-0.459451,-0.748323,-0.548740,-1.216483,0.442778,3
2016-12-27,40109,-0.400429,0.482288,-1.044767,-0.895646,-1.019871,-1.021607,-0.688430,-0.963624,0.514872,-0.905778,-0.364868,-0.019813,-0.380632,0.230599,-0.171891,0.824904,-0.717188,1.738543,3
2016-12-27,1019,0.203984,0.531990,0.401584,-0.103067,0.636692,0.602503,-0.325152,-0.272762,-0.230360,-0.133307,-0.925628,-1.074035,-0.342753,-1.190394,-0.620716,-0.938175,-0.069066,-1.134872,4

In [11]:
df_shift = {}
for i in df.columns:
    df_shift[i + '_pre']= df[i].shift()
df_shift = pd.DataFrame(df_shift)
df_total = pd.concat([df,df_shift],axis=1)
df_total

,fips,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,...,TS_pre,WS10M_pre,WS10M_MAX_pre,WS10M_MIN_pre,WS10M_RANGE_pre,WS50M_pre,WS50M_MAX_pre,WS50M_MIN_pre,WS50M_RANGE_pre,score_pre
date,,,,,,,,,,,,,,,,,,,,,
2000-01-04,13293,0.667669,0.605742,-0.025995,-0.162733,0.196127,0.193740,-0.279952,-0.336161,0.060936,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-04,51155,0.586479,-0.415565,-0.187427,-0.573271,-0.003411,-0.007160,-0.753719,-0.909549,0.184737,...,-0.190941,0.184897,-0.367359,1.126956,-1.246620,0.782961,0.237211,1.236782,-0.866626,3.0
2000-01-04,8071,-0.400429,-2.302659,-1.324002,-1.463810,-1.949404,-1.919691,-1.106115,-1.633975,1.046487,...,-0.579757,0.157409,-0.228341,0.626952,-0.730360,0.725758,0.187646,1.054347,-0.762055,1.0
2000-01-04,46109,-0.396821,0.374866,-1.491979,-2.477243,-2.334651,-2.309556,-2.599402,-2.337890,-1.451375,...,-1.458034,0.696179,0.922422,0.475435,0.895092,0.800562,1.214339,0.079763,1.488483,0.0
2000-01-04,9011,2.327552,0.770883,0.089626,-0.307000,0.412458,0.410553,-0.674200,-0.091888,-1.715969,...,-2.338892,1.037033,1.532558,-0.001841,2.024730,0.589350,1.193097,-0.405129,1.915858,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-27,28015,-0.223616,0.886321,0.360135,-0.006889,0.638667,0.593552,-0.284137,0.032113,-0.905195,...,-0.135888,-0.909135,-1.008388,-0.304874,-1.123944,-0.581114,-1.101030,0.012550,-1.421304,5.0
2016-12-27,19079,-0.400429,0.410139,-1.190929,-1.597391,-1.358692,-1.356772,-1.489481,-1.625584,-0.087139,...,-0.032662,-0.859656,-0.977495,-0.380632,-1.037049,-0.664719,-0.736377,-0.405129,-0.557461,2.0
2016-12-27,40077,-0.400429,0.613759,-0.878971,-0.643624,-0.704759,-0.725229,-0.504280,-0.555260,-0.019170,...,-1.656744,0.520254,0.879944,0.202706,1.027991,0.523347,0.888630,0.094165,1.052015,0.0
2016-12-27,40109,-0.400429,0.482288,-1.044767,-0.895646,-1.019871,-1.021607,-0.688430,-0.963624,0.514872,...,-0.669219,-0.892642,-0.950463,-1.183668,-0.459451,-0.748323,-0.548740,-1.216483,0.442778,3.0
2016-12-27,1019,0.203984,0.531990,0.401584,-0.103067,0.636692,0.602503,-0.325152,-0.272762,-0.230360,...,-0.905778,-0.364868,-0.019813,-0.380632,0.230599,-0.171891,0.824904,-0.717188,1.738543,3.0

In [12]:
df_total.fillna(value=0,inplace=True)
df_total

,fips,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,...,TS_pre,WS10M_pre,WS10M_MAX_pre,WS10M_MIN_pre,WS10M_RANGE_pre,WS50M_pre,WS50M_MAX_pre,WS50M_MIN_pre,WS50M_RANGE_pre,score_pre
date,,,,,,,,,,,,,,,,,,,,,
2000-01-04,13293,0.667669,0.605742,-0.025995,-0.162733,0.196127,0.193740,-0.279952,-0.336161,0.060936,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2000-01-04,51155,0.586479,-0.415565,-0.187427,-0.573271,-0.003411,-0.007160,-0.753719,-0.909549,0.184737,...,-0.190941,0.184897,-0.367359,1.126956,-1.246620,0.782961,0.237211,1.236782,-0.866626,3.0
2000-01-04,8071,-0.400429,-2.302659,-1.324002,-1.463810,-1.949404,-1.919691,-1.106115,-1.633975,1.046487,...,-0.579757,0.157409,-0.228341,0.626952,-0.730360,0.725758,0.187646,1.054347,-0.762055,1.0
2000-01-04,46109,-0.396821,0.374866,-1.491979,-2.477243,-2.334651,-2.309556,-2.599402,-2.337890,-1.451375,...,-1.458034,0.696179,0.922422,0.475435,0.895092,0.800562,1.214339,0.079763,1.488483,0.0
2000-01-04,9011,2.327552,0.770883,0.089626,-0.307000,0.412458,0.410553,-0.674200,-0.091888,-1.715969,...,-2.338892,1.037033,1.532558,-0.001841,2.024730,0.589350,1.193097,-0.405129,1.915858,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-27,28015,-0.223616,0.886321,0.360135,-0.006889,0.638667,0.593552,-0.284137,0.032113,-0.905195,...,-0.135888,-0.909135,-1.008388,-0.304874,-1.123944,-0.581114,-1.101030,0.012550,-1.421304,5.0
2016-12-27,19079,-0.400429,0.410139,-1.190929,-1.597391,-1.358692,-1.356772,-1.489481,-1.625584,-0.087139,...,-0.032662,-0.859656,-0.977495,-0.380632,-1.037049,-0.664719,-0.736377,-0.405129,-0.557461,2.0
2016-12-27,40077,-0.400429,0.613759,-0.878971,-0.643624,-0.704759,-0.725229,-0.504280,-0.555260,-0.019170,...,-1.656744,0.520254,0.879944,0.202706,1.027991,0.523347,0.888630,0.094165,1.052015,0.0
2016-12-27,40109,-0.400429,0.482288,-1.044767,-0.895646,-1.019871,-1.021607,-0.688430,-0.963624,0.514872,...,-0.669219,-0.892642,-0.950463,-1.183668,-0.459451,-0.748323,-0.548740,-1.216483,0.442778,3.0
2016-12-27,1019,0.203984,0.531990,0.401584,-0.103067,0.636692,0.602503,-0.325152,-0.272762,-0.230360,...,-0.905778,-0.364868,-0.019813,-0.380632,0.230599,-0.171891,0.824904,-0.717188,1.738543,3.0

In [13]:
df_total.corr().score.sort_values().head(100)

PS                -0.106304
PRECTOT           -0.057844
fips              -0.055629
WS50M_MIN         -0.049703
WS10M_MIN         -0.031247
WS50M             -0.030570
WS50M_MAX         -0.010411
WS10M             -0.009904
WS10M_MAX_pre     -0.008929
WS10M_RANGE_pre   -0.008838
WS50M_MIN_pre     -0.007857
WS10M_pre         -0.006509
WS10M_MIN_pre     -0.004428
PRECTOT_pre       -0.004199
WS50M_pre         -0.004042
WS50M_MAX_pre     -0.002999
WS50M_RANGE_pre    0.003595
fips_pre           0.004496
WS10M_MAX          0.005758
T2MDEW             0.017985
T2MWET             0.018797
QV2M               0.021082
PS_pre             0.023285
WS10M_RANGE        0.028687
WS50M_RANGE        0.033702
T2M_RANGE_pre      0.055190
T2MDEW_pre         0.058033
T2MWET_pre         0.058377
QV2M_pre           0.060006
T2M_MIN_pre        0.096711
T2M_pre            0.101432
TS_pre             0.102553
T2M_MAX_pre        0.105857
T2M_MIN            0.158055
T2M                0.182815
TS                 0.188828
T2M_RANGE          0.210610
T2M_MAX            0.214523
score_pre          0.226904
score              1.000000
Name: score, dtype: float64

In [14]:
X = df_total[['T2M_MAX','T2M_RANGE','TS','T2M','T2M_MIN','T2M_MAX_pre','TS_pre','T2M_pre']]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,df_total['score'], test_size=0.2, random_state=1)

clf2 = DecisionTreeClassifier()
clf2 = clf2.fit(X_train,y_train)

In [18]:
y_pred = clf2.predict(X_test)

In [19]:
print(metrics.classification_report(y_test, y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.389     0.347     0.367     84739
           1      0.352     0.323     0.337     84589
           2      0.460     0.465     0.462     85005
           3      0.526     0.548     0.537     84830
           4      0.632     0.679     0.655     85095
           5      0.830     0.879     0.854     84966

    accuracy                          0.541    509224
   macro avg      0.532     0.540     0.535    509224
weighted avg      0.532     0.541     0.536    509224

In [20]:
metrics.mean_absolute_error(y_test, y_pred)

0.8627185678601166

In [29]:
df_total

,fips,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,...,TS_pre,WS10M_pre,WS10M_MAX_pre,WS10M_MIN_pre,WS10M_RANGE_pre,WS50M_pre,WS50M_MAX_pre,WS50M_MIN_pre,WS50M_RANGE_pre,score_pre
date,,,,,,,,,,,,,,,,,,,,,
2000-01-04,13293,0.667669,0.605742,-0.025995,-0.162733,0.196127,0.193740,-0.279952,-0.336161,0.060936,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2000-01-04,51155,0.586479,-0.415565,-0.187427,-0.573271,-0.003411,-0.007160,-0.753719,-0.909549,0.184737,...,-0.190941,0.184897,-0.367359,1.126956,-1.246620,0.782961,0.237211,1.236782,-0.866626,3.0
2000-01-04,8071,-0.400429,-2.302659,-1.324002,-1.463810,-1.949404,-1.919691,-1.106115,-1.633975,1.046487,...,-0.579757,0.157409,-0.228341,0.626952,-0.730360,0.725758,0.187646,1.054347,-0.762055,1.0
2000-01-04,46109,-0.396821,0.374866,-1.491979,-2.477243,-2.334651,-2.309556,-2.599402,-2.337890,-1.451375,...,-1.458034,0.696179,0.922422,0.475435,0.895092,0.800562,1.214339,0.079763,1.488483,0.0
2000-01-04,9011,2.327552,0.770883,0.089626,-0.307000,0.412458,0.410553,-0.674200,-0.091888,-1.715969,...,-2.338892,1.037033,1.532558,-0.001841,2.024730,0.589350,1.193097,-0.405129,1.915858,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-27,28015,-0.223616,0.886321,0.360135,-0.006889,0.638667,0.593552,-0.284137,0.032113,-0.905195,...,-0.135888,-0.909135,-1.008388,-0.304874,-1.123944,-0.581114,-1.101030,0.012550,-1.421304,5.0
2016-12-27,19079,-0.400429,0.410139,-1.190929,-1.597391,-1.358692,-1.356772,-1.489481,-1.625584,-0.087139,...,-0.032662,-0.859656,-0.977495,-0.380632,-1.037049,-0.664719,-0.736377,-0.405129,-0.557461,2.0
2016-12-27,40077,-0.400429,0.613759,-0.878971,-0.643624,-0.704759,-0.725229,-0.504280,-0.555260,-0.019170,...,-1.656744,0.520254,0.879944,0.202706,1.027991,0.523347,0.888630,0.094165,1.052015,0.0
2016-12-27,40109,-0.400429,0.482288,-1.044767,-0.895646,-1.019871,-1.021607,-0.688430,-0.963624,0.514872,...,-0.669219,-0.892642,-0.950463,-1.183668,-0.459451,-0.748323,-0.548740,-1.216483,0.442778,3.0
2016-12-27,1019,0.203984,0.531990,0.401584,-0.103067,0.636692,0.602503,-0.325152,-0.272762,-0.230360,...,-0.905778,-0.364868,-0.019813,-0.380632,0.230599,-0.171891,0.824904,-0.717188,1.738543,3.0

In [38]:
from sklearn.decomposition import PCA

pca01 = PCA(n_components=3)
principComp = pca01.fit_transform(df_total)

In [39]:
pca01.explained_variance_ratio_

array([5.25500109e-01, 4.74499808e-01, 2.45367769e-08])

In [40]:
import numpy as np
np.cumsum(pca01.explained_variance_ratio_)

array([0.52550011, 0.99999992, 0.99999994])

In [41]:
principComp = pd.DataFrame(principComp)

X_train, X_test, y_train, y_test = train_test_split(principComp, df_total['score'], test_size=0.25, random_state=1)


clf3 = DecisionTreeClassifier()
clf3 = clf3.fit(X_train,y_train)

In [42]:
y_pred = clf3.predict(X_test)

In [43]:
print(metrics.classification_report(y_test, y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.300     0.299     0.299    105994
           1      0.219     0.219     0.219    105739
           2      0.200     0.201     0.201    106158
           3      0.205     0.206     0.206    106087
           4      0.240     0.237     0.239    106458
           5      0.378     0.379     0.379    106094

    accuracy                          0.257    636530
   macro avg      0.257     0.257     0.257    636530
weighted avg      0.257     0.257     0.257    636530

In [1]:
import pandas as pd
df = pd.read_csv('train.csv')

df

,fips,date,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,...,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
0,1001,2000-01-04,15.95,100.29,6.42,11.40,6.09,6.10,18.09,2.16,...,11.31,3.84,5.67,2.08,3.59,6.73,9.31,3.74,5.58,1.0
1,1001,2000-01-11,1.33,100.40,6.63,11.48,7.84,7.84,18.88,5.72,...,10.43,1.76,2.48,1.05,1.43,3.55,6.38,1.71,4.67,2.0
2,1001,2000-01-18,1.11,100.39,9.53,14.28,13.26,13.26,18.04,8.98,...,14.19,2.63,3.60,1.67,1.92,5.19,6.40,3.84,2.55,2.0
3,1001,2000-01-25,0.00,100.11,2.05,-0.78,-7.93,-7.72,5.65,-5.46,...,-0.61,3.35,4.59,2.28,2.32,5.75,8.03,3.96,4.07,2.0
4,1001,2000-02-01,0.00,101.00,3.36,2.06,-1.73,-1.70,11.02,-4.21,...,1.88,2.03,2.74,0.88,1.86,4.18,6.38,1.27,5.11,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2756791,56043,2016-11-29,0.04,82.47,2.19,-4.27,-9.36,-9.26,-1.51,-7.22,...,-4.38,6.93,10.27,3.08,7.18,9.42,12.59,5.62,6.97,0.0
2756792,56043,2016-12-06,0.13,82.59,0.91,-11.96,-18.65,-17.90,-6.85,-15.24,...,-11.98,2.27,3.97,0.95,3.02,3.07,5.16,0.83,4.33,0.0
2756793,56043,2016-12-13,0.02,82.86,1.40,-9.56,-14.18,-13.95,-2.69,-13.01,...,-10.95,3.64,6.59,1.28,5.31,5.33,8.35,2.13,6.22,0.0
2756794,56043,2016-12-20,0.32,83.12,2.73,-2.55,-6.90,-6.84,2.66,-7.77,...,-3.94,6.16,8.43,3.44,4.99,8.99,10.14,6.67,3.47,0.0
2756795,56043,2016-12-27,0.16,82.88,1.63,-7.97,-13.49,-12.81,-1.39,-13.60,...,-9.41,5.90,7.63,3.61,4.02,8.58,10.39,5.92,4.47,0.0

In [2]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_to_normalize = df[['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']]
scaler.fit(df_to_normalize)
df_to_normalize = scaler.transform(df_to_normalize)

df_normal = pd.DataFrame(df_to_normalize)
df_normal.columns = ['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']
df_normal

,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE
0,2.118487,0.669024,-0.308331,-0.136661,-0.094076,-0.097099,-0.058357,-0.504787,1.157200,-0.148775,0.149339,0.179012,0.118696,0.158369,0.520851,0.522172,0.293099,0.400169
1,-0.221616,0.689228,-0.263853,-0.129369,0.077533,0.074437,0.009729,-0.169513,0.473697,-0.227409,-0.976419,-1.043576,-0.648553,-0.953236,-0.862631,-0.510749,-0.669012,-0.017067
2,-0.256830,0.687391,0.350364,0.125863,0.609028,0.608762,-0.062666,0.137508,-0.541652,0.108576,-0.505549,-0.614329,-0.186714,-0.701066,-0.149137,-0.503698,0.340493,-0.989089
3,-0.434498,0.635965,-1.233892,-1.246922,-1.468902,-1.459529,-1.130498,-1.222424,-0.033977,-1.213921,-0.115864,-0.234905,0.267677,-0.495214,0.094495,0.070930,0.397367,-0.292168
4,-0.434498,0.799426,-0.956435,-0.988043,-0.860919,-0.866054,-0.667685,-1.104701,0.986324,-0.991420,-0.830287,-0.943929,-0.775186,-0.731944,-0.588545,-0.510749,-0.877548,0.184674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2756791,-0.428096,-2.603885,-1.204240,-1.565050,-1.609131,-1.611349,-1.747582,-1.388177,-1.371266,-1.550801,1.821738,1.941993,0.863599,2.005898,1.691154,1.678479,1.184118,1.037486
2756792,-0.413690,-2.581845,-1.475343,-2.266028,-2.520125,-2.463114,-2.207810,-2.143485,-0.707575,-2.229921,-0.700392,-0.472524,-0.723043,-0.134971,-1.071458,-0.940839,-1.086084,-0.172957
2756793,-0.431297,-2.532256,-1.371561,-2.047257,-2.081789,-2.073707,-1.849281,-1.933468,-0.229618,-2.137882,0.041093,0.531609,-0.477225,1.043536,-0.088229,0.183740,-0.469954,0.693610
2756794,-0.383279,-2.484503,-1.089869,-1.408265,-1.367899,-1.372775,-1.388191,-1.439975,-0.204853,-1.511483,1.404991,1.236801,1.131763,0.878854,1.504080,0.814774,1.681761,-0.567268
2756795,-0.408888,-2.528582,-1.322848,-1.902322,-2.014126,-1.961322,-1.737240,-1.989033,0.238433,-2.000271,1.264272,0.930195,1.258397,0.379661,1.325706,0.902907,1.326301,-0.108767

In [3]:
df_total = {}
df_total['date'] = pd.to_datetime(df['date'])
df_total['score'] = df['score'].astype(int)

df_total = pd.DataFrame(df_total)

df_total = pd.concat([df_total,df_normal],axis=1)
df_total.set_index('date',inplace=True)
df_total

,score,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE
date,,,,,,,,,,,,,,,,,,,
2000-01-04,1,2.118487,0.669024,-0.308331,-0.136661,-0.094076,-0.097099,-0.058357,-0.504787,1.157200,-0.148775,0.149339,0.179012,0.118696,0.158369,0.520851,0.522172,0.293099,0.400169
2000-01-11,2,-0.221616,0.689228,-0.263853,-0.129369,0.077533,0.074437,0.009729,-0.169513,0.473697,-0.227409,-0.976419,-1.043576,-0.648553,-0.953236,-0.862631,-0.510749,-0.669012,-0.017067
2000-01-18,2,-0.256830,0.687391,0.350364,0.125863,0.609028,0.608762,-0.062666,0.137508,-0.541652,0.108576,-0.505549,-0.614329,-0.186714,-0.701066,-0.149137,-0.503698,0.340493,-0.989089
2000-01-25,2,-0.434498,0.635965,-1.233892,-1.246922,-1.468902,-1.459529,-1.130498,-1.222424,-0.033977,-1.213921,-0.115864,-0.234905,0.267677,-0.495214,0.094495,0.070930,0.397367,-0.292168
2000-02-01,1,-0.434498,0.799426,-0.956435,-0.988043,-0.860919,-0.866054,-0.667685,-1.104701,0.986324,-0.991420,-0.830287,-0.943929,-0.775186,-0.731944,-0.588545,-0.510749,-0.877548,0.184674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-11-29,0,-0.428096,-2.603885,-1.204240,-1.565050,-1.609131,-1.611349,-1.747582,-1.388177,-1.371266,-1.550801,1.821738,1.941993,0.863599,2.005898,1.691154,1.678479,1.184118,1.037486
2016-12-06,0,-0.413690,-2.581845,-1.475343,-2.266028,-2.520125,-2.463114,-2.207810,-2.143485,-0.707575,-2.229921,-0.700392,-0.472524,-0.723043,-0.134971,-1.071458,-0.940839,-1.086084,-0.172957
2016-12-13,0,-0.431297,-2.532256,-1.371561,-2.047257,-2.081789,-2.073707,-1.849281,-1.933468,-0.229618,-2.137882,0.041093,0.531609,-0.477225,1.043536,-0.088229,0.183740,-0.469954,0.693610
2016-12-20,0,-0.383279,-2.484503,-1.089869,-1.408265,-1.367899,-1.372775,-1.388191,-1.439975,-0.204853,-1.511483,1.404991,1.236801,1.131763,0.878854,1.504080,0.814774,1.681761,-0.567268
2016-12-27,0,-0.408888,-2.528582,-1.322848,-1.902322,-2.014126,-1.961322,-1.737240,-1.989033,0.238433,-2.000271,1.264272,0.930195,1.258397,0.379661,1.325706,0.902907,1.326301,-0.108767

In [4]:
df_shift = {}
for i in df_total.columns:
    df_shift[i + '_pre']= df_total[i].shift()
df_shift = pd.DataFrame(df_shift)
df_total = pd.concat([df_total,df_shift],axis=1)
df_total

,score,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,...,T2M_RANGE_pre,TS_pre,WS10M_pre,WS10M_MAX_pre,WS10M_MIN_pre,WS10M_RANGE_pre,WS50M_pre,WS50M_MAX_pre,WS50M_MIN_pre,WS50M_RANGE_pre
date,,,,,,,,,,,,,,,,,,,,,
2000-01-04,1,2.118487,0.669024,-0.308331,-0.136661,-0.094076,-0.097099,-0.058357,-0.504787,1.157200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-11,2,-0.221616,0.689228,-0.263853,-0.129369,0.077533,0.074437,0.009729,-0.169513,0.473697,...,1.157200,-0.148775,0.149339,0.179012,0.118696,0.158369,0.520851,0.522172,0.293099,0.400169
2000-01-18,2,-0.256830,0.687391,0.350364,0.125863,0.609028,0.608762,-0.062666,0.137508,-0.541652,...,0.473697,-0.227409,-0.976419,-1.043576,-0.648553,-0.953236,-0.862631,-0.510749,-0.669012,-0.017067
2000-01-25,2,-0.434498,0.635965,-1.233892,-1.246922,-1.468902,-1.459529,-1.130498,-1.222424,-0.033977,...,-0.541652,0.108576,-0.505549,-0.614329,-0.186714,-0.701066,-0.149137,-0.503698,0.340493,-0.989089
2000-02-01,1,-0.434498,0.799426,-0.956435,-0.988043,-0.860919,-0.866054,-0.667685,-1.104701,0.986324,...,-0.033977,-1.213921,-0.115864,-0.234905,0.267677,-0.495214,0.094495,0.070930,0.397367,-0.292168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-11-29,0,-0.428096,-2.603885,-1.204240,-1.565050,-1.609131,-1.611349,-1.747582,-1.388177,-1.371266,...,-0.442593,-1.239835,-0.343180,-0.395872,-1.058249,0.204686,-0.562441,-0.884433,-1.147697,-0.039992
2016-12-06,0,-0.413690,-2.581845,-1.475343,-2.266028,-2.520125,-2.463114,-2.207810,-2.143485,-0.707575,...,-1.371266,-1.550801,1.821738,1.941993,0.863599,2.005898,1.691154,1.678479,1.184118,1.037486
2016-12-13,0,-0.431297,-2.532256,-1.371561,-2.047257,-2.081789,-2.073707,-1.849281,-1.933468,-0.229618,...,-0.707575,-2.229921,-0.700392,-0.472524,-0.723043,-0.134971,-1.071458,-0.940839,-1.086084,-0.172957
2016-12-20,0,-0.383279,-2.484503,-1.089869,-1.408265,-1.367899,-1.372775,-1.388191,-1.439975,-0.204853,...,-0.229618,-2.137882,0.041093,0.531609,-0.477225,1.043536,-0.088229,0.183740,-0.469954,0.693610
2016-12-27,0,-0.408888,-2.528582,-1.322848,-1.902322,-2.014126,-1.961322,-1.737240,-1.989033,0.238433,...,-0.204853,-1.511483,1.404991,1.236801,1.131763,0.878854,1.504080,0.814774,1.681761,-0.567268

In [5]:
df_total.fillna(value=0,inplace=True)

In [6]:
from sklearn.decomposition import PCA

pca01 = PCA(n_components=5)
principComp = pca01.fit_transform(df_total)

In [7]:
import numpy as np
np.cumsum(pca01.explained_variance_ratio_)

array([0.36602317, 0.54647048, 0.63639201, 0.72100734, 0.77444401])

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

principComp = pd.DataFrame(principComp)

X_train, X_test, y_train, y_test = train_test_split(principComp, df_total['score'], test_size=0.25, random_state=1)


clf4 = DecisionTreeClassifier()
clf4 = clf4.fit(X_train,y_train)

In [9]:
y_pred = clf4.predict(X_test)

In [10]:
from sklearn import metrics

print(metrics.classification_report(y_test, y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.972     0.972     0.972    448986
           1      0.820     0.819     0.820    105828
           2      0.835     0.830     0.832     66307
           3      0.844     0.849     0.847     42460
           4      0.850     0.858     0.854     20161
           5      0.870     0.883     0.876      5457

    accuracy                          0.923    689199
   macro avg      0.865     0.869     0.867    689199
weighted avg      0.923     0.923     0.923    689199

In [11]:
metrics.mean_absolute_error(y_test, y_pred)

0.07780191207474184

In [12]:
pca02 = PCA(n_components=10)
principComp2 = pca02.fit_transform(df_total)
np.cumsum(pca02.explained_variance_ratio_)

array([0.36602317, 0.54647048, 0.63639201, 0.72100734, 0.77444401,
       0.81584561, 0.85665232, 0.89036118, 0.92153913, 0.94457454])

In [13]:
principComp2 = pd.DataFrame(principComp2)

X_train, X_test, y_train, y_test = train_test_split(principComp2, df_total['score'], test_size=0.25, random_state=1)


clf5 = DecisionTreeClassifier()
clf5 = clf5.fit(X_train,y_train)

In [14]:
y_pred = clf5.predict(X_test)

In [15]:
print(metrics.classification_report(y_test, y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.989     0.990     0.990    448986
           1      0.931     0.930     0.930    105828
           2      0.937     0.935     0.936     66307
           3      0.947     0.946     0.946     42460
           4      0.950     0.952     0.951     20161
           5      0.960     0.955     0.958      5457

    accuracy                          0.971    689199
   macro avg      0.952     0.951     0.952    689199
weighted avg      0.971     0.971     0.971    689199

In [16]:
df_test = pd.read_csv('test_timeseries.csv')
df_test

,fips,date,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,...,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
0,1001,2019-01-01,2.25,100.51,9.69,14.71,13.55,13.52,17.38,10.92,...,14.63,1.20,1.50,0.79,0.71,2.74,4.01,1.23,2.78,0.0000
1,1001,2019-01-02,4.94,100.48,8.65,13.05,11.83,11.74,17.76,9.54,...,13.06,1.02,1.35,0.32,1.03,2.13,3.37,0.56,2.81,NaN
2,1001,2019-01-03,20.74,100.03,8.59,12.12,11.67,11.67,13.74,10.44,...,12.12,1.83,4.23,0.34,3.88,3.41,7.49,0.72,6.77,NaN
3,1001,2019-01-04,16.17,99.47,7.93,11.80,10.38,9.59,18.19,5.44,...,11.72,3.75,5.25,2.34,2.91,6.78,9.61,4.90,4.71,NaN
4,1001,2019-01-05,0.01,100.39,5.32,7.91,4.73,4.71,14.37,3.68,...,7.75,2.32,2.90,1.69,1.21,4.42,5.87,3.15,2.72,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2271943,56043,2020-12-27,3.83,82.91,2.77,-3.61,-6.77,-5.19,0.24,-9.07,...,-5.88,2.98,6.04,0.72,5.31,4.56,7.68,1.03,6.66,NaN
2271944,56043,2020-12-28,0.00,83.04,1.82,-7.31,-12.06,-9.68,-1.48,-11.51,...,-10.61,1.83,2.81,0.10,2.72,2.52,3.69,0.14,3.56,NaN
2271945,56043,2020-12-29,0.00,82.78,1.87,-7.38,-11.79,-9.59,-0.88,-11.39,...,-10.81,2.70,6.22,0.18,6.04,3.84,7.66,0.29,7.37,3.5182
2271946,56043,2020-12-30,0.01,82.87,1.57,-6.40,-13.94,-10.17,1.33,-12.16,...,-8.74,2.93,4.10,1.62,2.48,4.42,6.05,2.79,3.26,NaN
2271947,56043,2020-12-31,0.00,82.82,2.13,-3.83,-10.12,-6.98,2.16,-8.57,...,-6.61,2.16,3.72,0.31,3.41,3.39,6.46,0.41,6.06,NaN

In [17]:
df_test = df_test.dropna()

df_test['score'] = df_test['score'].astype(int)

/home/nastaran/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [18]:
df_test

,fips,date,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,...,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
0,1001,2019-01-01,2.25,100.51,9.69,14.71,13.55,13.52,17.38,10.92,...,14.63,1.20,1.50,0.79,0.71,2.74,4.01,1.23,2.78,0
7,1001,2019-01-08,0.05,100.57,8.75,13.15,12.01,11.98,20.04,9.36,...,13.05,2.33,3.40,1.68,1.72,5.13,6.51,3.67,2.85,0
14,1001,2019-01-15,0.00,101.07,4.04,3.91,0.94,0.96,9.40,1.02,...,3.91,1.73,2.40,1.36,1.04,3.28,4.13,2.39,1.75,0
21,1001,2019-01-22,0.03,101.14,4.96,6.03,3.81,3.08,12.43,-1.63,...,6.08,3.68,4.57,2.49,2.07,6.65,8.56,5.01,3.55,0
28,1001,2019-01-29,5.79,100.36,3.69,2.23,-0.41,-1.03,7.33,-5.19,...,2.18,3.10,4.52,1.71,2.81,5.62,6.96,3.60,3.35,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2271917,56043,2020-12-01,1.24,83.55,2.58,-2.42,-7.58,-5.00,0.38,-6.79,...,-2.74,5.42,8.52,2.85,5.68,7.81,10.34,5.13,5.21,3
2271924,56043,2020-12-08,0.00,83.70,2.05,1.32,-10.65,-4.67,8.08,-3.27,...,-1.57,3.05,3.85,2.36,1.49,4.73,6.30,3.85,2.45,3
2271931,56043,2020-12-15,0.14,82.90,2.04,-5.19,-10.64,-7.91,0.29,-8.63,...,-6.81,2.88,3.90,1.68,2.21,4.39,6.50,2.83,3.66,3
2271938,56043,2020-12-22,1.64,82.00,3.13,-0.05,-5.29,-2.67,6.87,-7.05,...,-0.82,8.83,13.78,6.64,7.14,11.90,17.31,9.05,8.25,3
2271945,56043,2020-12-29,0.00,82.78,1.87,-7.38,-11.79,-9.59,-0.88,-11.39,...,-10.81,2.70,6.22,0.18,6.04,3.84,7.66,0.29,7.37,3

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_to_normalize = df_test[['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']]
scaler.fit(df_to_normalize)
df_to_normalize = scaler.transform(df_to_normalize)

df_normal = pd.DataFrame(df_to_normalize)
df_normal.columns = ['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']
df_normal

,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE
0,-0.083493,0.706985,0.301901,0.172940,0.561810,0.569065,-0.092256,0.303861,-1.130537,0.159317,-1.298466,-1.429709,-0.850312,-1.318635,-1.231647,-1.355922,-0.898529,-0.881193
1,-0.434297,0.718014,0.112263,0.030995,0.415490,0.418974,0.137535,0.158815,-0.030253,0.018002,-0.661595,-0.682436,-0.152282,-0.796556,-0.147327,-0.446160,0.306493,-0.848841
2,-0.442269,0.809927,-0.837942,-0.809753,-0.636306,-0.655054,-0.781627,-0.616622,-0.629934,-0.799475,-0.999757,-1.075738,-0.403259,-1.148054,-0.986654,-1.312254,-0.325650,-1.357228
3,-0.437486,0.822794,-0.652339,-0.616854,-0.363618,-0.448435,-0.519873,-0.863013,0.851017,-0.605392,0.099267,-0.222274,0.483004,-0.615637,0.542282,0.299845,0.968267,-0.525322
4,0.480983,0.679411,-0.908552,-0.962616,-0.764574,-0.849003,-0.960449,-1.194015,0.449492,-0.954206,-0.227622,-0.241939,-0.128753,-0.233123,0.074981,-0.282403,0.271923,-0.617756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326335,-0.244544,-2.410671,-1.132486,-1.385720,-1.445818,-1.235926,-1.560841,-1.342780,-0.945418,-1.394249,1.079935,1.331267,0.765354,1.250409,1.068563,0.947595,1.027531,0.241880
326336,-0.442269,-2.383098,-1.239409,-1.045417,-1.737508,-1.203764,-0.895658,-1.015497,0.144437,-1.289604,-0.255802,-0.505451,0.381045,-0.915445,-0.328803,-0.522580,0.395388,-1.033709
326337,-0.419946,-2.530157,-1.241426,-1.637762,-1.736558,-1.519540,-1.568616,-1.513859,-0.486532,-1.758268,-0.351614,-0.485786,-0.152282,-0.543270,-0.483058,-0.449799,-0.108351,-0.474483
326338,-0.180761,-2.695599,-1.021527,-1.170073,-1.228238,-1.008840,-1.000187,-1.366954,0.817122,-1.222525,3.001818,3.400033,3.737865,2.005098,2.924157,3.484012,2.963468,1.646877
326339,-0.442269,-2.552216,-1.275722,-1.837031,-1.845823,-1.683275,-1.669689,-1.770479,-0.074577,-2.116026,-0.453063,0.426674,-1.328737,1.436497,-0.732587,-0.027670,-1.362759,1.240167

In [20]:
df_total = {}
df_total['date'] = pd.to_datetime(df_test['date'])
df_total['score'] = df_test['score'].astype(int)

df_total = pd.DataFrame(df_total)

df_total = pd.concat([df_total,df_normal],axis=1)
df_total.set_index('date',inplace=True)
df_total

,score,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE
date,,,,,,,,,,,,,,,,,,,
2000-01-04,1,2.118487,0.669024,-0.308331,-0.136661,-0.094076,-0.097099,-0.058357,-0.504787,1.157200,-0.148775,0.149339,0.179012,0.118696,0.158369,0.520851,0.522172,0.293099,0.400169
2000-01-11,2,-0.221616,0.689228,-0.263853,-0.129369,0.077533,0.074437,0.009729,-0.169513,0.473697,-0.227409,-0.976419,-1.043576,-0.648553,-0.953236,-0.862631,-0.510749,-0.669012,-0.017067
2000-01-18,2,-0.256830,0.687391,0.350364,0.125863,0.609028,0.608762,-0.062666,0.137508,-0.541652,0.108576,-0.505549,-0.614329,-0.186714,-0.701066,-0.149137,-0.503698,0.340493,-0.989089
2000-01-25,2,-0.434498,0.635965,-1.233892,-1.246922,-1.468902,-1.459529,-1.130498,-1.222424,-0.033977,-1.213921,-0.115864,-0.234905,0.267677,-0.495214,0.094495,0.070930,0.397367,-0.292168
2000-02-01,1,-0.434498,0.799426,-0.956435,-0.988043,-0.860919,-0.866054,-0.667685,-1.104701,0.986324,-0.991420,-0.830287,-0.943929,-0.775186,-0.731944,-0.588545,-0.510749,-0.877548,0.184674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-11-29,0,-0.428096,-2.603885,-1.204240,-1.565050,-1.609131,-1.611349,-1.747582,-1.388177,-1.371266,-1.550801,1.821738,1.941993,0.863599,2.005898,1.691154,1.678479,1.184118,1.037486
2016-12-06,0,-0.413690,-2.581845,-1.475343,-2.266028,-2.520125,-2.463114,-2.207810,-2.143485,-0.707575,-2.229921,-0.700392,-0.472524,-0.723043,-0.134971,-1.071458,-0.940839,-1.086084,-0.172957
2016-12-13,0,-0.431297,-2.532256,-1.371561,-2.047257,-2.081789,-2.073707,-1.849281,-1.933468,-0.229618,-2.137882,0.041093,0.531609,-0.477225,1.043536,-0.088229,0.183740,-0.469954,0.693610
2016-12-20,0,-0.383279,-2.484503,-1.089869,-1.408265,-1.367899,-1.372775,-1.388191,-1.439975,-0.204853,-1.511483,1.404991,1.236801,1.131763,0.878854,1.504080,0.814774,1.681761,-0.567268
2016-12-27,0,-0.408888,-2.528582,-1.322848,-1.902322,-2.014126,-1.961322,-1.737240,-1.989033,0.238433,-2.000271,1.264272,0.930195,1.258397,0.379661,1.325706,0.902907,1.326301,-0.108767