In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
df3 = pd.read_csv('train.csv')

df3

,fips,date,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,...,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
0,1001,2000-01-04,15.95,100.29,6.42,11.40,6.09,6.10,18.09,2.16,...,11.31,3.84,5.67,2.08,3.59,6.73,9.31,3.74,5.58,1.0
1,1001,2000-01-11,1.33,100.40,6.63,11.48,7.84,7.84,18.88,5.72,...,10.43,1.76,2.48,1.05,1.43,3.55,6.38,1.71,4.67,2.0
2,1001,2000-01-18,1.11,100.39,9.53,14.28,13.26,13.26,18.04,8.98,...,14.19,2.63,3.60,1.67,1.92,5.19,6.40,3.84,2.55,2.0
3,1001,2000-01-25,0.00,100.11,2.05,-0.78,-7.93,-7.72,5.65,-5.46,...,-0.61,3.35,4.59,2.28,2.32,5.75,8.03,3.96,4.07,2.0
4,1001,2000-02-01,0.00,101.00,3.36,2.06,-1.73,-1.70,11.02,-4.21,...,1.88,2.03,2.74,0.88,1.86,4.18,6.38,1.27,5.11,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2756791,56043,2016-11-29,0.04,82.47,2.19,-4.27,-9.36,-9.26,-1.51,-7.22,...,-4.38,6.93,10.27,3.08,7.18,9.42,12.59,5.62,6.97,0.0
2756792,56043,2016-12-06,0.13,82.59,0.91,-11.96,-18.65,-17.90,-6.85,-15.24,...,-11.98,2.27,3.97,0.95,3.02,3.07,5.16,0.83,4.33,0.0
2756793,56043,2016-12-13,0.02,82.86,1.40,-9.56,-14.18,-13.95,-2.69,-13.01,...,-10.95,3.64,6.59,1.28,5.31,5.33,8.35,2.13,6.22,0.0
2756794,56043,2016-12-20,0.32,83.12,2.73,-2.55,-6.90,-6.84,2.66,-7.77,...,-3.94,6.16,8.43,3.44,4.99,8.99,10.14,6.67,3.47,0.0
2756795,56043,2016-12-27,0.16,82.88,1.63,-7.97,-13.49,-12.81,-1.39,-13.60,...,-9.41,5.90,7.63,3.61,4.02,8.58,10.39,5.92,4.47,0.0

In [2]:
df3['score'] = df3['score'].astype(int)

In [3]:
class_0_count,class_1_count,class_2_count,class_3_count,class_4_count,class_5_count = df3.score.value_counts()
print(class_0_count,class_1_count,class_2_count,class_3_count,class_4_count,class_5_count)

1794623 424353 265995 169049 80970 21806

In [4]:
class_0 = df3[df3['score'] == 0]
class_1 = df3[df3['score'] == 1]
class_2 = df3[df3['score'] == 2]
class_3 = df3[df3['score'] == 3]
class_4 = df3[df3['score'] == 4]
class_5 = df3[df3['score'] == 5]

In [5]:
class_0_under = class_0.sample(class_1_count)
class_2_under = class_2.sample(class_1_count,replace=True)
class_3_under = class_3.sample(class_1_count,replace=True)
class_4_under = class_4.sample(class_1_count,replace=True)
class_5_under = class_5.sample(class_1_count,replace=True)

df = pd.concat([class_0_under,class_1,class_2_under,class_3_under,class_4_under,class_5_under], axis=0)
df

,fips,date,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,...,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
1705070,37133,2004-11-30,0.03,102.16,5.44,9.41,5.09,5.09,15.27,4.16,...,9.56,2.19,3.94,1.09,2.85,3.42,7.35,1.23,6.12,0
1045821,24043,2000-12-05,0.08,98.64,2.30,-0.60,-6.89,-6.73,5.08,-4.73,...,-0.77,3.86,6.47,1.96,4.50,6.91,10.05,4.41,5.64,0
1641342,36113,2007-07-10,4.20,96.60,16.16,23.73,20.95,20.95,28.57,18.89,...,23.62,1.33,1.92,0.65,1.27,3.14,4.49,1.30,3.19,0
527325,17067,2008-07-29,15.64,98.83,18.12,24.79,23.14,23.14,28.20,21.22,...,24.70,2.62,3.69,1.08,2.61,4.12,6.79,1.86,4.93,0
1111706,26113,2005-08-30,0.04,97.07,10.39,20.28,14.14,14.14,26.55,13.76,...,20.95,2.62,4.51,1.17,3.34,3.92,6.32,1.23,5.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143650,6009,2016-03-01,0.00,95.48,6.70,13.67,7.04,7.05,19.40,8.74,...,11.42,1.99,3.18,0.31,2.86,3.20,5.26,0.93,4.33,5
2361057,48345,2014-05-20,0.00,92.90,5.87,30.24,4.09,4.10,40.26,20.08,...,31.83,7.00,8.94,4.78,4.16,9.49,12.54,5.63,6.91,5
2049383,45057,2007-12-04,0.00,99.58,2.31,6.15,-6.83,-6.46,13.36,0.02,...,5.24,1.70,2.71,0.74,1.97,3.36,5.16,1.74,3.42,5
1668863,37051,2007-12-25,0.03,101.48,3.99,6.22,0.81,0.84,11.57,3.41,...,5.87,3.38,5.01,2.40,2.61,5.81,7.72,4.26,3.46,5
1871378,40025,2013-04-30,0.00,85.36,3.34,22.84,-3.91,-3.76,32.88,13.14,...,24.81,3.36,5.69,0.77,4.92,5.18,9.62,0.99,8.63,5

In [6]:
class_0_count,class_1_count,class_2_count,class_3_count,class_4_count,class_5_count = df.score.value_counts()
print(class_0_count,class_1_count,class_2_count,class_3_count,class_4_count,class_5_count)

424353 424353 424353 424353 424353 424353

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_to_normalize = df[['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']]
scaler.fit(df_to_normalize)
df_to_normalize = scaler.transform(df_to_normalize)
df_to_normalize

array([[-0.39569055,  1.05595915, -0.50322323, ..., -0.17616753,
        -0.85671551,  0.58488744],
       [-0.38667492,  0.49166493, -1.18817968, ...,  0.77937579,
         0.67015368,  0.36666098],
       [ 0.3562128 ,  0.16463078,  1.83522681, ..., -1.18833564,
        -0.82310518, -0.74720326],
       ...,
       [-0.40109993,  0.64235713, -1.18599829, ..., -0.95121933,
        -0.61184026, -0.64263642],
       [-0.39569055,  0.94694776, -0.81952478, ..., -0.0452227 ,
         0.59813155, -0.62445088],
       [-0.40109993, -1.63726326, -0.96131512, ...,  0.62719667,
        -0.97195092,  1.72603   ]])

In [8]:
df_normal = pd.DataFrame(df_to_normalize)
df_normal.columns = ['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']
df_normal

,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE
0,-0.395691,1.055959,-0.503223,-0.476367,-0.159942,-0.165766,-0.503423,-0.442838,-0.307543,-0.467252,-0.765672,-0.521081,-0.600887,-0.284595,-0.910785,-0.176168,-0.856716,0.584887
1,-0.386675,0.491665,-1.188180,-1.367712,-1.343172,-1.341184,-1.356174,-1.271703,-0.623342,-1.355880,0.152192,0.455604,0.058349,0.558777,0.624720,0.779376,0.670154,0.366661
2,0.356213,0.164631,1.835227,0.798765,1.406505,1.411402,0.609589,0.930522,-0.654922,0.742247,-1.238345,-1.300884,-0.934294,-1.092187,-1.033977,-1.188336,-0.823105,-0.747203
3,2.418988,0.522124,2.262779,0.893154,1.622805,1.629183,0.578626,1.147761,-1.308383,0.835153,-0.529336,-0.617591,-0.608465,-0.407267,-0.602804,-0.374354,-0.554223,0.043868
4,-0.393887,0.239977,0.576565,0.491558,0.733901,0.734194,0.440545,0.452223,0.100567,0.512563,-0.529336,-0.301037,-0.540268,-0.034139,-0.690798,-0.540690,-0.856716,0.121156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2546113,-0.401100,-0.014917,-0.228368,-0.097033,0.032654,0.029143,-0.157803,-0.015819,-0.419287,-0.307247,-0.875596,-0.814472,-1.191927,-0.279484,-1.007579,-0.915829,-1.000760,-0.228915
2546114,-0.401100,-0.428519,-0.409423,1.378452,-0.258709,-0.264215,1.587869,1.041472,1.895763,1.448504,1.877997,1.409127,2.195185,0.384991,1.759850,1.660599,1.255934,0.944052
2546115,-0.401100,0.642357,-1.185998,-0.766655,-1.337246,-1.314334,-0.663261,-0.828834,0.236603,-0.838876,-1.034985,-0.995912,-0.866097,-0.734393,-0.937183,-0.951219,-0.611840,-0.642636
2546116,-0.395691,0.946948,-0.819525,-0.760422,-0.582665,-0.588399,-0.813058,-0.512765,-1.024164,-0.784680,-0.111625,-0.108016,0.391756,-0.407267,0.140750,-0.045223,0.598132,-0.624451
2546117,-0.401100,-1.637263,-0.961315,0.719515,-1.048846,-1.045838,0.970272,0.394417,1.788877,0.844615,-0.122617,0.154492,-0.843365,0.773453,-0.136433,0.627197,-0.971951,1.726030

In [9]:
df_score = df[['score']]
df_score = df_score.reset_index(drop=True)
df_score

         score
0            0
1            0
2            0
3            0
4            0
...        ...
2546113      5
2546114      5
2546115      5
2546116      5
2546117      5

[2546118 rows x 1 columns]

In [10]:
df_normal = df_normal.loc[df_normal.index.drop_duplicates(keep=False),:]
df_score = df_score.loc[df_score.index.drop_duplicates(keep=False),:]
df_score

         score
0            0
1            0
2            0
3            0
4            0
...        ...
2546113      5
2546114      5
2546115      5
2546116      5
2546117      5

[2546118 rows x 1 columns]

In [11]:
df_ready = pd.concat([df_normal, df_score], axis=1, join='outer')
df_ready

,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
0,-0.395691,1.055959,-0.503223,-0.476367,-0.159942,-0.165766,-0.503423,-0.442838,-0.307543,-0.467252,-0.765672,-0.521081,-0.600887,-0.284595,-0.910785,-0.176168,-0.856716,0.584887,0
1,-0.386675,0.491665,-1.188180,-1.367712,-1.343172,-1.341184,-1.356174,-1.271703,-0.623342,-1.355880,0.152192,0.455604,0.058349,0.558777,0.624720,0.779376,0.670154,0.366661,0
2,0.356213,0.164631,1.835227,0.798765,1.406505,1.411402,0.609589,0.930522,-0.654922,0.742247,-1.238345,-1.300884,-0.934294,-1.092187,-1.033977,-1.188336,-0.823105,-0.747203,0
3,2.418988,0.522124,2.262779,0.893154,1.622805,1.629183,0.578626,1.147761,-1.308383,0.835153,-0.529336,-0.617591,-0.608465,-0.407267,-0.602804,-0.374354,-0.554223,0.043868,0
4,-0.393887,0.239977,0.576565,0.491558,0.733901,0.734194,0.440545,0.452223,0.100567,0.512563,-0.529336,-0.301037,-0.540268,-0.034139,-0.690798,-0.540690,-0.856716,0.121156,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2546113,-0.401100,-0.014917,-0.228368,-0.097033,0.032654,0.029143,-0.157803,-0.015819,-0.419287,-0.307247,-0.875596,-0.814472,-1.191927,-0.279484,-1.007579,-0.915829,-1.000760,-0.228915,5
2546114,-0.401100,-0.428519,-0.409423,1.378452,-0.258709,-0.264215,1.587869,1.041472,1.895763,1.448504,1.877997,1.409127,2.195185,0.384991,1.759850,1.660599,1.255934,0.944052,5
2546115,-0.401100,0.642357,-1.185998,-0.766655,-1.337246,-1.314334,-0.663261,-0.828834,0.236603,-0.838876,-1.034985,-0.995912,-0.866097,-0.734393,-0.937183,-0.951219,-0.611840,-0.642636,5
2546116,-0.395691,0.946948,-0.819525,-0.760422,-0.582665,-0.588399,-0.813058,-0.512765,-1.024164,-0.784680,-0.111625,-0.108016,0.391756,-0.407267,0.140750,-0.045223,0.598132,-0.624451,5
2546117,-0.401100,-1.637263,-0.961315,0.719515,-1.048846,-1.045838,0.970272,0.394417,1.788877,0.844615,-0.122617,0.154492,-0.843365,0.773453,-0.136433,0.627197,-0.971951,1.726030,5

In [12]:
a = df_ready.corr()
a.sort_values(by='score',ascending=False)

,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
score,-0.058703,-0.106463,0.022458,0.184604,0.019300,0.020115,0.216266,0.159896,0.211176,0.190631,-0.009834,0.005812,-0.031605,0.028998,-0.030847,-0.010457,-0.050504,0.034391,1.000000
T2M_MAX,-0.008726,0.173090,0.747634,0.984124,0.797437,0.798432,1.000000,0.939735,0.454366,0.980851,-0.165214,-0.181686,-0.081448,-0.185625,-0.161456,-0.162056,-0.094993,-0.118231,0.216266
T2M_RANGE,-0.323779,-0.189889,-0.102362,0.298199,-0.039112,-0.038801,0.454366,0.122411,1.000000,0.298238,-0.050550,-0.017556,-0.078498,0.029702,-0.018508,0.056792,-0.111352,0.178397,0.211176
TS,0.053865,0.217749,0.811818,0.997243,0.852464,0.853509,0.980851,0.978324,0.298238,1.000000,-0.137325,-0.161073,-0.050656,-0.179103,-0.146039,-0.157575,-0.064283,-0.141553,0.190631
T2M,0.059615,0.221780,0.821741,1.000000,0.863453,0.864447,0.984124,0.981986,0.298199,0.997243,-0.160307,-0.184476,-0.068045,-0.198360,-0.162801,-0.176981,-0.076062,-0.155330,0.184604
T2M_MIN,0.114546,0.265724,0.872245,0.981986,0.903456,0.904445,0.939735,1.000000,0.122411,0.978324,-0.164668,-0.195682,-0.060615,-0.218209,-0.172779,-0.202348,-0.063096,-0.200195,0.159896
WS50M_RANGE,0.008428,-0.178721,-0.279286,-0.155330,-0.276315,-0.275889,-0.118231,-0.200195,0.178397,-0.141553,0.417732,0.597935,-0.050685,0.825882,0.382440,0.682577,-0.130037,1.000000,0.034391
WS10M_RANGE,0.022219,-0.233768,-0.289451,-0.198360,-0.306396,-0.305773,-0.185625,-0.218209,0.029702,-0.179103,0.700239,0.867823,0.220943,1.000000,0.640025,0.807012,0.222673,0.825882,0.028998
QV2M,0.263679,0.370202,1.000000,0.821741,0.962489,0.963685,0.747634,0.872245,-0.102362,0.811818,-0.209460,-0.254847,-0.071130,-0.289451,-0.201431,-0.256545,-0.053099,-0.279286,0.022458
T2MWET,0.242230,0.434793,0.963685,0.864447,0.999960,1.000000,0.798432,0.904445,-0.038801,0.853509,-0.222697,-0.269392,-0.075479,-0.305773,-0.199288,-0.253322,-0.052314,-0.275889,0.020115
T2MDEW,0.242219,0.434366,0.962489,0.863453,1.000000,0.999960,0.797437,0.903456,-0.039112,0.852464,-0.223120,-0.269892,-0.075537,-0.306396,-0.199468,-0.253612,-0.052258,-0.276315,0.019300
WS10M_MAX,0.020766,-0.167584,-0.254847,-0.184476,-0.269892,-0.269392,-0.181686,-0.195682,-0.017556,-0.161073,0.949509,1.000000,0.676330,0.867823,0.907236,0.943866,0.649080,0.597935,0.005812
WS10M,0.014090,-0.102397,-0.209460,-0.160307,-0.223120,-0.222697,-0.165214,-0.164668,-0.050550,-0.137325,1.000000,0.949509,0.825666,0.700239,0.966352,0.907885,0.790577,0.417732,-0.009834
WS50M_MAX,0.041244,-0.110377,-0.256545,-0.176981,-0.253612,-0.253322,-0.162056,-0.202348,0.056792,-0.157575,0.907885,0.943866,0.656300,0.807012,0.917168,1.000000,0.635846,0.682577,-0.010457
WS50M,0.038815,-0.052131,-0.201431,-0.162801,-0.199468,-0.199288,-0.161456,-0.172779,-0.018508,-0.146039,0.966352,0.907236,0.831955,0.640025,1.000000,0.917168,0.840442,0.382440,-0.030847
WS10M_MIN,0.007825,0.017625,-0.071130,-0.068045,-0.075537,-0.075479,-0.081448,-0.060615,-0.078498,-0.050656,0.825666,0.676330,1.000000,0.220943,0.831955,0.656300,0.943942,-0.050685,-0.031605
WS50M_MIN,0.047056,0.038995,-0.053099,-0.076062,-0.052258,-0.052314,-0.094993,-0.063096,-0.111352,-0.064283,0.790577,0.649080,0.943942,0.222673,0.840442,0.635846,1.000000,-0.130037,-0.050504
PRECTOT,1.000000,0.089598,0.263679,0.059615,0.242219,0.242230,-0.008726,0.114546,-0.323779,0.053865,0.014090,0.020766,0.007825,0.022219,0.038815,0.041244,0.047056,0.008428,-0.058703
PS,0.089598,1.000000,0.370202,0.221780,0.434366,0.434793,0.173090,0.265724,-0.189889,0.217749,-0.102397,-0.167584,0.017625,-0.233768,-0.052131,-0.110377,0.038995,-0.178721,-0.106463

In [13]:
x_train = df_ready[['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']]
y_train = df_ready[['score']]

In [14]:
import pandas as pd
df_test = pd.read_csv('test_timeseries.csv')
df_test = df_test.dropna()

df_test['score'] = df_test['score'].astype(int)

In [15]:
y_test = df_test[['score']]
df_test = df_test[['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                              ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']]

scaler = StandardScaler()
scaler.fit(df_test)
df_test = scaler.transform(df_test)


df_test = pd.DataFrame(df_test)
df_test.columns = ['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']
df_test

,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE
0,-0.083493,0.706985,0.301901,0.172940,0.561810,0.569065,-0.092256,0.303861,-1.130537,0.159317,-1.298466,-1.429709,-0.850312,-1.318635,-1.231647,-1.355922,-0.898529,-0.881193
1,-0.434297,0.718014,0.112263,0.030995,0.415490,0.418974,0.137535,0.158815,-0.030253,0.018002,-0.661595,-0.682436,-0.152282,-0.796556,-0.147327,-0.446160,0.306493,-0.848841
2,-0.442269,0.809927,-0.837942,-0.809753,-0.636306,-0.655054,-0.781627,-0.616622,-0.629934,-0.799475,-0.999757,-1.075738,-0.403259,-1.148054,-0.986654,-1.312254,-0.325650,-1.357228
3,-0.437486,0.822794,-0.652339,-0.616854,-0.363618,-0.448435,-0.519873,-0.863013,0.851017,-0.605392,0.099267,-0.222274,0.483004,-0.615637,0.542282,0.299845,0.968267,-0.525322
4,0.480983,0.679411,-0.908552,-0.962616,-0.764574,-0.849003,-0.960449,-1.194015,0.449492,-0.954206,-0.227622,-0.241939,-0.128753,-0.233123,0.074981,-0.282403,0.271923,-0.617756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326335,-0.244544,-2.410671,-1.132486,-1.385720,-1.445818,-1.235926,-1.560841,-1.342780,-0.945418,-1.394249,1.079935,1.331267,0.765354,1.250409,1.068563,0.947595,1.027531,0.241880
326336,-0.442269,-2.383098,-1.239409,-1.045417,-1.737508,-1.203764,-0.895658,-1.015497,0.144437,-1.289604,-0.255802,-0.505451,0.381045,-0.915445,-0.328803,-0.522580,0.395388,-1.033709
326337,-0.419946,-2.530157,-1.241426,-1.637762,-1.736558,-1.519540,-1.568616,-1.513859,-0.486532,-1.758268,-0.351614,-0.485786,-0.152282,-0.543270,-0.483058,-0.449799,-0.108351,-0.474483
326338,-0.180761,-2.695599,-1.021527,-1.170073,-1.228238,-1.008840,-1.000187,-1.366954,0.817122,-1.222525,3.001818,3.400033,3.737865,2.005098,2.924157,3.484012,2.963468,1.646877
326339,-0.442269,-2.552216,-1.275722,-1.837031,-1.845823,-1.683275,-1.669689,-1.770479,-0.074577,-2.116026,-0.453063,0.426674,-1.328737,1.436497,-0.732587,-0.027670,-1.362759,1.240167

In [16]:
x_test = df_test[['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']]

In [17]:
from sklearn.neural_network import MLPClassifier
import numpy as np

y_train_2 = y_train.values.ravel()

clf = MLPClassifier(random_state=1, max_iter=300).fit(x_train, y_train_2)
y_pred = clf.predict(x_test)

In [18]:
y_pred = pd.DataFrame(y_pred)
y_pred.columns = ['score']


from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.3509713795428081

In [19]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred, labels=[1,2], average='micro')
precision = precision_score(y_test, y_pred, labels=[1,2], average='micro')
recall

0.09307317073170732

In [20]:
precision

0.08769672010589792