In [4]:
import pandas as pd
ds = pd.read_csv('test_timeseries.csv')

In [5]:
ds

,fips,date,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,...,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
0,1001,2019-01-01,2.25,100.51,9.69,14.71,13.55,13.52,17.38,10.92,...,14.63,1.20,1.50,0.79,0.71,2.74,4.01,1.23,2.78,0.0000
1,1001,2019-01-02,4.94,100.48,8.65,13.05,11.83,11.74,17.76,9.54,...,13.06,1.02,1.35,0.32,1.03,2.13,3.37,0.56,2.81,NaN
2,1001,2019-01-03,20.74,100.03,8.59,12.12,11.67,11.67,13.74,10.44,...,12.12,1.83,4.23,0.34,3.88,3.41,7.49,0.72,6.77,NaN
3,1001,2019-01-04,16.17,99.47,7.93,11.80,10.38,9.59,18.19,5.44,...,11.72,3.75,5.25,2.34,2.91,6.78,9.61,4.90,4.71,NaN
4,1001,2019-01-05,0.01,100.39,5.32,7.91,4.73,4.71,14.37,3.68,...,7.75,2.32,2.90,1.69,1.21,4.42,5.87,3.15,2.72,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2271943,56043,2020-12-27,3.83,82.91,2.77,-3.61,-6.77,-5.19,0.24,-9.07,...,-5.88,2.98,6.04,0.72,5.31,4.56,7.68,1.03,6.66,NaN
2271944,56043,2020-12-28,0.00,83.04,1.82,-7.31,-12.06,-9.68,-1.48,-11.51,...,-10.61,1.83,2.81,0.10,2.72,2.52,3.69,0.14,3.56,NaN
2271945,56043,2020-12-29,0.00,82.78,1.87,-7.38,-11.79,-9.59,-0.88,-11.39,...,-10.81,2.70,6.22,0.18,6.04,3.84,7.66,0.29,7.37,3.5182
2271946,56043,2020-12-30,0.01,82.87,1.57,-6.40,-13.94,-10.17,1.33,-12.16,...,-8.74,2.93,4.10,1.62,2.48,4.42,6.05,2.79,3.26,NaN
2271947,56043,2020-12-31,0.00,82.82,2.13,-3.83,-10.12,-6.98,2.16,-8.57,...,-6.61,2.16,3.72,0.31,3.41,3.39,6.46,0.41,6.06,NaN

In [6]:
import pandas as pd

df1 = pd.read_csv("train_timeseries.csv",nrows=10000000)
df1
df1 = df1.dropna()
df1.isnull().sum()

fips           0
date           0
PRECTOT        0
PS             0
QV2M           0
T2M            0
T2MDEW         0
T2MWET         0
T2M_MAX        0
T2M_MIN        0
T2M_RANGE      0
TS             0
WS10M          0
WS10M_MAX      0
WS10M_MIN      0
WS10M_RANGE    0
WS50M          0
WS50M_MAX      0
WS50M_MIN      0
WS50M_RANGE    0
score          0
dtype: int64

In [7]:
df2 = pd.read_csv("train_timeseries.csv",skiprows=10000000,nrows=10000000)
df2 = df2.dropna()
df2.isnull().sum()

30093          0
2005-03-14     0
2.58           0
79.97          0
2.25           0
-4.86          0
-9.39          0
-9.31          0
-1.22          0
-7.41          0
6.19           0
-5.01          0
3.18           0
4.51           0
1.94           0
2.57           0
5.03           0
6.67           0
3.4            0
3.27           0
Unnamed: 20    0
dtype: int64

In [8]:
df1

,fips,date,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,...,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
3,1001,2000-01-04,15.95,100.29,6.42,11.40,6.09,6.10,18.09,2.16,...,11.31,3.84,5.67,2.08,3.59,6.73,9.31,3.74,5.58,1.0
10,1001,2000-01-11,1.33,100.40,6.63,11.48,7.84,7.84,18.88,5.72,...,10.43,1.76,2.48,1.05,1.43,3.55,6.38,1.71,4.67,2.0
17,1001,2000-01-18,1.11,100.39,9.53,14.28,13.26,13.26,18.04,8.98,...,14.19,2.63,3.60,1.67,1.92,5.19,6.40,3.84,2.55,2.0
24,1001,2000-01-25,0.00,100.11,2.05,-0.78,-7.93,-7.72,5.65,-5.46,...,-0.61,3.35,4.59,2.28,2.32,5.75,8.03,3.96,4.07,2.0
31,1001,2000-02-01,0.00,101.00,3.36,2.06,-1.73,-1.70,11.02,-4.21,...,1.88,2.03,2.74,0.88,1.86,4.18,6.38,1.27,5.11,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999965,30093,2005-02-08,0.38,79.84,1.90,-8.60,-11.28,-11.20,-2.35,-12.34,...,-8.83,2.73,3.99,2.02,1.98,4.54,5.73,3.65,2.08,4.0
9999972,30093,2005-02-15,0.21,80.07,1.46,-10.39,-14.10,-13.93,-4.39,-15.32,...,-10.85,2.21,3.37,1.32,2.05,3.55,4.72,2.51,2.21,4.0
9999979,30093,2005-02-22,0.02,80.16,1.94,-4.17,-11.09,-10.91,3.19,-9.52,...,-6.61,1.40,2.44,0.19,2.24,2.05,3.40,0.26,3.14,4.0
9999986,30093,2005-03-01,0.78,79.78,2.97,-0.48,-6.18,-6.12,5.40,-4.55,...,-0.90,2.40,3.13,1.66,1.47,3.87,4.72,3.14,1.58,4.0
9999993,30093,2005-03-08,0.20,80.44,3.63,2.24,-3.69,-3.64,9.28,-1.63,...,2.15,3.65,5.31,2.63,2.68,6.38,7.60,4.95,2.65,4.0

In [9]:
df2

,30093,2005-03-14,2.58,79.97,2.25,-4.86,-9.39,-9.31,-1.22,-7.41,...,-5.01,3.18,4.51,1.94,2.57,5.03,6.67,3.4,3.27,Unnamed: 20
0,30093,2005-03-15,1.16,79.49,2.85,-3.41,-6.80,-6.77,1.07,-7.37,...,-3.57,2.76,3.79,1.90,1.88,4.64,5.95,3.53,2.42,4.0
7,30093,2005-03-22,2.49,79.09,3.43,-2.03,-4.50,-4.48,2.07,-5.26,...,-2.22,2.39,4.66,0.76,3.90,3.85,6.80,1.31,5.49,4.0
14,30093,2005-03-29,2.09,78.62,2.66,-2.73,-7.63,-7.57,1.59,-5.69,...,-2.62,3.60,5.33,2.47,2.87,5.83,7.65,4.34,3.31,4.0
21,30093,2005-04-05,0.39,80.46,2.79,0.68,-6.79,-6.71,8.04,-5.38,...,0.51,2.26,3.37,1.27,2.09,3.60,5.55,1.93,3.61,4.0
28,30093,2005-04-12,0.43,79.44,3.83,4.05,-3.01,-2.98,10.32,-1.38,...,3.83,4.07,6.74,1.35,5.39,7.05,9.75,2.41,7.34,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9300647,56043,2016-11-29,0.04,82.47,2.19,-4.27,-9.36,-9.26,-1.51,-7.22,...,-4.38,6.93,10.27,3.08,7.18,9.42,12.59,5.62,6.97,0.0
9300654,56043,2016-12-06,0.13,82.59,0.91,-11.96,-18.65,-17.90,-6.85,-15.24,...,-11.98,2.27,3.97,0.95,3.02,3.07,5.16,0.83,4.33,0.0
9300661,56043,2016-12-13,0.02,82.86,1.40,-9.56,-14.18,-13.95,-2.69,-13.01,...,-10.95,3.64,6.59,1.28,5.31,5.33,8.35,2.13,6.22,0.0
9300668,56043,2016-12-20,0.32,83.12,2.73,-2.55,-6.90,-6.84,2.66,-7.77,...,-3.94,6.16,8.43,3.44,4.99,8.99,10.14,6.67,3.47,0.0
9300675,56043,2016-12-27,0.16,82.88,1.63,-7.97,-13.49,-12.81,-1.39,-13.60,...,-9.41,5.90,7.63,3.61,4.02,8.58,10.39,5.92,4.47,0.0

In [10]:
df2.columns = ['fips', 'date','PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE','score']
df2

,fips,date,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,...,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
0,30093,2005-03-15,1.16,79.49,2.85,-3.41,-6.80,-6.77,1.07,-7.37,...,-3.57,2.76,3.79,1.90,1.88,4.64,5.95,3.53,2.42,4.0
7,30093,2005-03-22,2.49,79.09,3.43,-2.03,-4.50,-4.48,2.07,-5.26,...,-2.22,2.39,4.66,0.76,3.90,3.85,6.80,1.31,5.49,4.0
14,30093,2005-03-29,2.09,78.62,2.66,-2.73,-7.63,-7.57,1.59,-5.69,...,-2.62,3.60,5.33,2.47,2.87,5.83,7.65,4.34,3.31,4.0
21,30093,2005-04-05,0.39,80.46,2.79,0.68,-6.79,-6.71,8.04,-5.38,...,0.51,2.26,3.37,1.27,2.09,3.60,5.55,1.93,3.61,4.0
28,30093,2005-04-12,0.43,79.44,3.83,4.05,-3.01,-2.98,10.32,-1.38,...,3.83,4.07,6.74,1.35,5.39,7.05,9.75,2.41,7.34,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9300647,56043,2016-11-29,0.04,82.47,2.19,-4.27,-9.36,-9.26,-1.51,-7.22,...,-4.38,6.93,10.27,3.08,7.18,9.42,12.59,5.62,6.97,0.0
9300654,56043,2016-12-06,0.13,82.59,0.91,-11.96,-18.65,-17.90,-6.85,-15.24,...,-11.98,2.27,3.97,0.95,3.02,3.07,5.16,0.83,4.33,0.0
9300661,56043,2016-12-13,0.02,82.86,1.40,-9.56,-14.18,-13.95,-2.69,-13.01,...,-10.95,3.64,6.59,1.28,5.31,5.33,8.35,2.13,6.22,0.0
9300668,56043,2016-12-20,0.32,83.12,2.73,-2.55,-6.90,-6.84,2.66,-7.77,...,-3.94,6.16,8.43,3.44,4.99,8.99,10.14,6.67,3.47,0.0
9300675,56043,2016-12-27,0.16,82.88,1.63,-7.97,-13.49,-12.81,-1.39,-13.60,...,-9.41,5.90,7.63,3.61,4.02,8.58,10.39,5.92,4.47,0.0

In [11]:
df3 = pd.concat([df1,df2])
df3

,fips,date,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,...,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
3,1001,2000-01-04,15.95,100.29,6.42,11.40,6.09,6.10,18.09,2.16,...,11.31,3.84,5.67,2.08,3.59,6.73,9.31,3.74,5.58,1.0
10,1001,2000-01-11,1.33,100.40,6.63,11.48,7.84,7.84,18.88,5.72,...,10.43,1.76,2.48,1.05,1.43,3.55,6.38,1.71,4.67,2.0
17,1001,2000-01-18,1.11,100.39,9.53,14.28,13.26,13.26,18.04,8.98,...,14.19,2.63,3.60,1.67,1.92,5.19,6.40,3.84,2.55,2.0
24,1001,2000-01-25,0.00,100.11,2.05,-0.78,-7.93,-7.72,5.65,-5.46,...,-0.61,3.35,4.59,2.28,2.32,5.75,8.03,3.96,4.07,2.0
31,1001,2000-02-01,0.00,101.00,3.36,2.06,-1.73,-1.70,11.02,-4.21,...,1.88,2.03,2.74,0.88,1.86,4.18,6.38,1.27,5.11,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9300647,56043,2016-11-29,0.04,82.47,2.19,-4.27,-9.36,-9.26,-1.51,-7.22,...,-4.38,6.93,10.27,3.08,7.18,9.42,12.59,5.62,6.97,0.0
9300654,56043,2016-12-06,0.13,82.59,0.91,-11.96,-18.65,-17.90,-6.85,-15.24,...,-11.98,2.27,3.97,0.95,3.02,3.07,5.16,0.83,4.33,0.0
9300661,56043,2016-12-13,0.02,82.86,1.40,-9.56,-14.18,-13.95,-2.69,-13.01,...,-10.95,3.64,6.59,1.28,5.31,5.33,8.35,2.13,6.22,0.0
9300668,56043,2016-12-20,0.32,83.12,2.73,-2.55,-6.90,-6.84,2.66,-7.77,...,-3.94,6.16,8.43,3.44,4.99,8.99,10.14,6.67,3.47,0.0
9300675,56043,2016-12-27,0.16,82.88,1.63,-7.97,-13.49,-12.81,-1.39,-13.60,...,-9.41,5.90,7.63,3.61,4.02,8.58,10.39,5.92,4.47,0.0

In [14]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
df3 = pd.read_csv('train.csv')
scaler = StandardScaler()
df4 = df3[['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']]
df5 = scaler.fit(df4)

In [15]:
df5 = scaler.transform(df4)
df5

array([[ 2.11848666,  0.66902437, -0.30833051, ...,  0.52217168,
         0.29309886,  0.40016908],
       [-0.22161613,  0.68922752, -0.26385272, ..., -0.51074884,
        -0.66901177, -0.01706694],
       [-0.25682972,  0.68739087,  0.35036434, ..., -0.50369819,
         0.34049348, -0.98908931],
       ...,
       [-0.43129703, -2.53225551, -1.37156142, ...,  0.18374038,
        -0.46995439,  0.6936098 ],
       [-0.3832785 , -2.48450263, -1.08986877, ...,  0.81477374,
         1.681761  , -0.56726828],
       [-0.40888838, -2.52858222, -1.32284766, ...,  0.90290689,
         1.32630141, -0.10876716]])

In [16]:
df5 = pd.DataFrame(df5)
df5.columns = ['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']
df5
df6 = df3[['score']]
df6 = pd.DataFrame(df6)
df5 = pd.concat([df5,df6],axis=1)
df5

,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
0,2.118487,0.669024,-0.308331,-0.136661,-0.094076,-0.097099,-0.058357,-0.504787,1.157200,-0.148775,0.149339,0.179012,0.118696,0.158369,0.520851,0.522172,0.293099,0.400169,1.0
1,-0.221616,0.689228,-0.263853,-0.129369,0.077533,0.074437,0.009729,-0.169513,0.473697,-0.227409,-0.976419,-1.043576,-0.648553,-0.953236,-0.862631,-0.510749,-0.669012,-0.017067,2.0
2,-0.256830,0.687391,0.350364,0.125863,0.609028,0.608762,-0.062666,0.137508,-0.541652,0.108576,-0.505549,-0.614329,-0.186714,-0.701066,-0.149137,-0.503698,0.340493,-0.989089,2.0
3,-0.434498,0.635965,-1.233892,-1.246922,-1.468902,-1.459529,-1.130498,-1.222424,-0.033977,-1.213921,-0.115864,-0.234905,0.267677,-0.495214,0.094495,0.070930,0.397367,-0.292168,2.0
4,-0.434498,0.799426,-0.956435,-0.988043,-0.860919,-0.866054,-0.667685,-1.104701,0.986324,-0.991420,-0.830287,-0.943929,-0.775186,-0.731944,-0.588545,-0.510749,-0.877548,0.184674,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2756791,-0.428096,-2.603885,-1.204240,-1.565050,-1.609131,-1.611349,-1.747582,-1.388177,-1.371266,-1.550801,1.821738,1.941993,0.863599,2.005898,1.691154,1.678479,1.184118,1.037486,0.0
2756792,-0.413690,-2.581845,-1.475343,-2.266028,-2.520125,-2.463114,-2.207810,-2.143485,-0.707575,-2.229921,-0.700392,-0.472524,-0.723043,-0.134971,-1.071458,-0.940839,-1.086084,-0.172957,0.0
2756793,-0.431297,-2.532256,-1.371561,-2.047257,-2.081789,-2.073707,-1.849281,-1.933468,-0.229618,-2.137882,0.041093,0.531609,-0.477225,1.043536,-0.088229,0.183740,-0.469954,0.693610,0.0
2756794,-0.383279,-2.484503,-1.089869,-1.408265,-1.367899,-1.372775,-1.388191,-1.439975,-0.204853,-1.511483,1.404991,1.236801,1.131763,0.878854,1.504080,0.814774,1.681761,-0.567268,0.0
2756795,-0.408888,-2.528582,-1.322848,-1.902322,-2.014126,-1.961322,-1.737240,-1.989033,0.238433,-2.000271,1.264272,0.930195,1.258397,0.379661,1.325706,0.902907,1.326301,-0.108767,0.0

In [17]:
a = df5.corr()
a

,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
PRECTOT,1.000000,0.068775,0.245081,0.093258,0.231035,0.230975,0.026773,0.144929,-0.304171,0.089598,0.049730,0.060981,0.023346,0.065755,0.069057,0.079508,0.057816,0.047477,-0.064059
PS,0.068775,1.000000,0.282412,0.164160,0.341234,0.341252,0.111979,0.208285,-0.225935,0.163830,-0.080747,-0.135905,0.022932,-0.198332,-0.043315,-0.091821,0.036238,-0.154479,-0.185663
QV2M,0.245081,0.282412,1.000000,0.870242,0.959385,0.960434,0.804338,0.906144,-0.071547,0.862559,-0.225449,-0.256452,-0.108789,-0.269203,-0.205971,-0.249961,-0.081554,-0.246203,-0.049752
T2M,0.093258,0.164160,0.870242,1.000000,0.913530,0.914218,0.983356,0.981629,0.244357,0.997515,-0.207874,-0.220192,-0.125407,-0.209030,-0.193196,-0.206444,-0.112579,-0.159589,0.088532
T2MDEW,0.231035,0.341234,0.959385,0.913530,1.000000,0.999970,0.854716,0.939934,-0.015643,0.905184,-0.238299,-0.268686,-0.115920,-0.280702,-0.204238,-0.245323,-0.082416,-0.239335,-0.056618
T2MWET,0.230975,0.341252,0.960434,0.914218,0.999970,1.000000,0.855401,0.940629,-0.015500,0.905911,-0.237971,-0.268292,-0.115882,-0.280199,-0.204143,-0.245147,-0.082497,-0.239029,-0.055894
T2M_MAX,0.026773,0.111979,0.804338,0.983356,0.854716,0.855401,1.000000,0.937762,0.407534,0.980101,-0.216764,-0.221671,-0.141911,-0.199614,-0.195727,-0.196236,-0.133234,-0.126331,0.126252
T2M_MIN,0.144929,0.208285,0.906144,0.981629,0.939934,0.940629,0.937762,1.000000,0.065037,0.979134,-0.206382,-0.225829,-0.112878,-0.225256,-0.197991,-0.225744,-0.096593,-0.200157,0.057611
T2M_RANGE,-0.304171,-0.225935,-0.071547,0.244357,-0.015643,-0.015500,0.407534,0.065037,1.000000,0.241564,-0.080163,-0.043127,-0.110952,0.018746,-0.041778,0.029737,-0.128844,0.163320,0.211284
TS,0.089598,0.163830,0.862559,0.997515,0.905184,0.905911,0.980101,0.979134,0.241564,1.000000,-0.189823,-0.202713,-0.110273,-0.196015,-0.180665,-0.193347,-0.102367,-0.152434,0.096073
WS10M,0.049730,-0.080747,-0.225449,-0.207874,-0.238299,-0.237971,-0.216764,-0.206382,-0.080163,-0.189823,1.000000,0.952217,0.833340,0.702896,0.966275,0.908750,0.795424,0.412412,0.021216
WS10M_MAX,0.060981,-0.135905,-0.256452,-0.220192,-0.268686,-0.268292,-0.221671,-0.225829,-0.043127,-0.202713,0.952217,1.000000,0.690087,0.866026,0.910717,0.946710,0.660428,0.592380,0.040860
WS10M_MIN,0.023346,0.022932,-0.108789,-0.125407,-0.115920,-0.115882,-0.141911,-0.112878,-0.110952,-0.110273,0.833340,0.690087,1.000000,0.235775,0.839187,0.666629,0.943983,-0.046209,-0.014314
WS10M_RANGE,0.065755,-0.198332,-0.269203,-0.209030,-0.280702,-0.280199,-0.199614,-0.225256,0.018746,-0.196015,0.702896,0.866026,0.235775,1.000000,0.643131,0.810677,0.234645,0.827364,0.064752
WS50M,0.069057,-0.043315,-0.205971,-0.193196,-0.204238,-0.204143,-0.195727,-0.197991,-0.041778,-0.180665,0.966275,0.910717,0.839187,0.643131,1.000000,0.917883,0.847885,0.373539,-0.002276
WS50M_MAX,0.079508,-0.091821,-0.249961,-0.206444,-0.245323,-0.245147,-0.196236,-0.225744,0.029737,-0.193347,0.908750,0.946710,0.666629,0.810677,0.917883,1.000000,0.646726,0.674944,0.017255
WS50M_MIN,0.057816,0.036238,-0.081554,-0.112579,-0.082416,-0.082497,-0.133234,-0.096593,-0.128844,-0.102367,0.795424,0.660428,0.943983,0.234645,0.847885,0.646726,1.000000,-0.126283,-0.030854
WS50M_RANGE,0.047477,-0.154479,-0.246203,-0.159589,-0.239335,-0.239029,-0.126331,-0.200157,0.163320,-0.152434,0.412412,0.592380,-0.046209,0.827364,0.373539,0.674944,-0.126283,1.000000,0.052290
score,-0.064059,-0.185663,-0.049752,0.088532,-0.056618,-0.055894,0.126252,0.057611,0.211284,0.096073,0.021216,0.040860,-0.014314,0.064752,-0.002276,0.017255,-0.030854,0.052290,1.000000

In [18]:
a.sort_values(by='score',ascending=False)

,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE,score
score,-0.064059,-0.185663,-0.049752,0.088532,-0.056618,-0.055894,0.126252,0.057611,0.211284,0.096073,0.021216,0.040860,-0.014314,0.064752,-0.002276,0.017255,-0.030854,0.052290,1.000000
T2M_RANGE,-0.304171,-0.225935,-0.071547,0.244357,-0.015643,-0.015500,0.407534,0.065037,1.000000,0.241564,-0.080163,-0.043127,-0.110952,0.018746,-0.041778,0.029737,-0.128844,0.163320,0.211284
T2M_MAX,0.026773,0.111979,0.804338,0.983356,0.854716,0.855401,1.000000,0.937762,0.407534,0.980101,-0.216764,-0.221671,-0.141911,-0.199614,-0.195727,-0.196236,-0.133234,-0.126331,0.126252
TS,0.089598,0.163830,0.862559,0.997515,0.905184,0.905911,0.980101,0.979134,0.241564,1.000000,-0.189823,-0.202713,-0.110273,-0.196015,-0.180665,-0.193347,-0.102367,-0.152434,0.096073
T2M,0.093258,0.164160,0.870242,1.000000,0.913530,0.914218,0.983356,0.981629,0.244357,0.997515,-0.207874,-0.220192,-0.125407,-0.209030,-0.193196,-0.206444,-0.112579,-0.159589,0.088532
WS10M_RANGE,0.065755,-0.198332,-0.269203,-0.209030,-0.280702,-0.280199,-0.199614,-0.225256,0.018746,-0.196015,0.702896,0.866026,0.235775,1.000000,0.643131,0.810677,0.234645,0.827364,0.064752
T2M_MIN,0.144929,0.208285,0.906144,0.981629,0.939934,0.940629,0.937762,1.000000,0.065037,0.979134,-0.206382,-0.225829,-0.112878,-0.225256,-0.197991,-0.225744,-0.096593,-0.200157,0.057611
WS50M_RANGE,0.047477,-0.154479,-0.246203,-0.159589,-0.239335,-0.239029,-0.126331,-0.200157,0.163320,-0.152434,0.412412,0.592380,-0.046209,0.827364,0.373539,0.674944,-0.126283,1.000000,0.052290
WS10M_MAX,0.060981,-0.135905,-0.256452,-0.220192,-0.268686,-0.268292,-0.221671,-0.225829,-0.043127,-0.202713,0.952217,1.000000,0.690087,0.866026,0.910717,0.946710,0.660428,0.592380,0.040860
WS10M,0.049730,-0.080747,-0.225449,-0.207874,-0.238299,-0.237971,-0.216764,-0.206382,-0.080163,-0.189823,1.000000,0.952217,0.833340,0.702896,0.966275,0.908750,0.795424,0.412412,0.021216
WS50M_MAX,0.079508,-0.091821,-0.249961,-0.206444,-0.245323,-0.245147,-0.196236,-0.225744,0.029737,-0.193347,0.908750,0.946710,0.666629,0.810677,0.917883,1.000000,0.646726,0.674944,0.017255
WS50M,0.069057,-0.043315,-0.205971,-0.193196,-0.204238,-0.204143,-0.195727,-0.197991,-0.041778,-0.180665,0.966275,0.910717,0.839187,0.643131,1.000000,0.917883,0.847885,0.373539,-0.002276
WS10M_MIN,0.023346,0.022932,-0.108789,-0.125407,-0.115920,-0.115882,-0.141911,-0.112878,-0.110952,-0.110273,0.833340,0.690087,1.000000,0.235775,0.839187,0.666629,0.943983,-0.046209,-0.014314
WS50M_MIN,0.057816,0.036238,-0.081554,-0.112579,-0.082416,-0.082497,-0.133234,-0.096593,-0.128844,-0.102367,0.795424,0.660428,0.943983,0.234645,0.847885,0.646726,1.000000,-0.126283,-0.030854
QV2M,0.245081,0.282412,1.000000,0.870242,0.959385,0.960434,0.804338,0.906144,-0.071547,0.862559,-0.225449,-0.256452,-0.108789,-0.269203,-0.205971,-0.249961,-0.081554,-0.246203,-0.049752
T2MWET,0.230975,0.341252,0.960434,0.914218,0.999970,1.000000,0.855401,0.940629,-0.015500,0.905911,-0.237971,-0.268292,-0.115882,-0.280199,-0.204143,-0.245147,-0.082497,-0.239029,-0.055894
T2MDEW,0.231035,0.341234,0.959385,0.913530,1.000000,0.999970,0.854716,0.939934,-0.015643,0.905184,-0.238299,-0.268686,-0.115920,-0.280702,-0.204238,-0.245323,-0.082416,-0.239335,-0.056618
PRECTOT,1.000000,0.068775,0.245081,0.093258,0.231035,0.230975,0.026773,0.144929,-0.304171,0.089598,0.049730,0.060981,0.023346,0.065755,0.069057,0.079508,0.057816,0.047477,-0.064059
PS,0.068775,1.000000,0.282412,0.164160,0.341234,0.341252,0.111979,0.208285,-0.225935,0.163830,-0.080747,-0.135905,0.022932,-0.198332,-0.043315,-0.091821,0.036238,-0.154479,-0.185663

In [19]:
x_train = df5[['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']]
y_train = df5[['score']]

In [20]:
df_test = pd.read_csv('test_timeseries.csv')
df_test = df_test.dropna()

scaler = StandardScaler()
y_test = df_test[['score']]
df_test = df_test[['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']]
scaler.fit(df_test)

df_test = scaler.transform(df_test)


df_test = pd.DataFrame(df_test)
df_test.columns = ['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']
df_test

,PRECTOT,PS,QV2M,T2M,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE
0,-0.083493,0.706985,0.301901,0.172940,0.561810,0.569065,-0.092256,0.303861,-1.130537,0.159317,-1.298466,-1.429709,-0.850312,-1.318635,-1.231647,-1.355922,-0.898529,-0.881193
1,-0.434297,0.718014,0.112263,0.030995,0.415490,0.418974,0.137535,0.158815,-0.030253,0.018002,-0.661595,-0.682436,-0.152282,-0.796556,-0.147327,-0.446160,0.306493,-0.848841
2,-0.442269,0.809927,-0.837942,-0.809753,-0.636306,-0.655054,-0.781627,-0.616622,-0.629934,-0.799475,-0.999757,-1.075738,-0.403259,-1.148054,-0.986654,-1.312254,-0.325650,-1.357228
3,-0.437486,0.822794,-0.652339,-0.616854,-0.363618,-0.448435,-0.519873,-0.863013,0.851017,-0.605392,0.099267,-0.222274,0.483004,-0.615637,0.542282,0.299845,0.968267,-0.525322
4,0.480983,0.679411,-0.908552,-0.962616,-0.764574,-0.849003,-0.960449,-1.194015,0.449492,-0.954206,-0.227622,-0.241939,-0.128753,-0.233123,0.074981,-0.282403,0.271923,-0.617756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326335,-0.244544,-2.410671,-1.132486,-1.385720,-1.445818,-1.235926,-1.560841,-1.342780,-0.945418,-1.394249,1.079935,1.331267,0.765354,1.250409,1.068563,0.947595,1.027531,0.241880
326336,-0.442269,-2.383098,-1.239409,-1.045417,-1.737508,-1.203764,-0.895658,-1.015497,0.144437,-1.289604,-0.255802,-0.505451,0.381045,-0.915445,-0.328803,-0.522580,0.395388,-1.033709
326337,-0.419946,-2.530157,-1.241426,-1.637762,-1.736558,-1.519540,-1.568616,-1.513859,-0.486532,-1.758268,-0.351614,-0.485786,-0.152282,-0.543270,-0.483058,-0.449799,-0.108351,-0.474483
326338,-0.180761,-2.695599,-1.021527,-1.170073,-1.228238,-1.008840,-1.000187,-1.366954,0.817122,-1.222525,3.001818,3.400033,3.737865,2.005098,2.924157,3.484012,2.963468,1.646877
326339,-0.442269,-2.552216,-1.275722,-1.837031,-1.845823,-1.683275,-1.669689,-1.770479,-0.074577,-2.116026,-0.453063,0.426674,-1.328737,1.436497,-0.732587,-0.027670,-1.362759,1.240167

In [21]:
x_test = df_test[['PRECTOT','PS','QV2M','T2M','T2MDEW','T2MWET','T2M_MAX',
                               'T2M_MIN','T2M_RANGE','TS','WS10M','WS10M_MAX','WS10M_MIN','WS10M_RANGE'
                                ,'WS50M','WS50M_MAX','WS50M_MIN','WS50M_RANGE']]

In [22]:
from sklearn.neural_network import MLPClassifier
import numpy as np

y_train_2 = y_train.values.ravel()
y_train_2 =y_train_2.astype('int')
y_train_2

array([1, 2, 2, ..., 0, 0, 0])

In [23]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(x_train, y_train_2)
y_pred = clf.predict(x_test)

In [24]:
y_pred = pd.DataFrame(y_pred)
y_pred.columns = ['score']

In [25]:
from sklearn.metrics import accuracy_score
y_test =y_test.astype('int')
print(accuracy_score(y_test, y_pred))

0.7988171845314702

In [13]:
y_pred[y_pred['score'] != 0]

        score
33          1
37          1
38          4
81          3
150         3
...       ...
326008      1
326180      3
326235      3
326278      3
326317      3

[13923 rows x 1 columns]

In [39]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred, labels=[1,2], average='micro')
precision = precision_score(y_test, y_pred, labels=[1,2], average='micro')
recall

0.033873170731707314

In [40]:
precision

0.1829101253819408

In [41]:
x_train = df5[['PRECTOT','T2M','T2M_MAX','T2M_RANGE','TS','WS10M_RANGE']]
y_train = df5[['score']]

In [42]:
df_test = pd.read_csv('test_timeseries.csv')
df_test = df_test.dropna()

scaler = StandardScaler()
y_test = df_test[['score']]
df_test = df_test[['PRECTOT','T2M','T2M_MAX','T2M_RANGE','TS','WS10M_RANGE']]
scaler.fit(df_test)

df_test = scaler.transform(df_test)


df_test = pd.DataFrame(df_test)
df_test.columns = ['PRECTOT','T2M','T2M_MAX','T2M_RANGE','TS','WS10M_RANGE']
df_test

         PRECTOT       T2M   T2M_MAX  T2M_RANGE        TS  WS10M_RANGE
0      -0.083493  0.172940 -0.092256  -1.130537  0.159317    -1.318635
1      -0.434297  0.030995  0.137535  -0.030253  0.018002    -0.796556
2      -0.442269 -0.809753 -0.781627  -0.629934 -0.799475    -1.148054
3      -0.437486 -0.616854 -0.519873   0.851017 -0.605392    -0.615637
4       0.480983 -0.962616 -0.960449   0.449492 -0.954206    -0.233123
...          ...       ...       ...        ...       ...          ...
326335 -0.244544 -1.385720 -1.560841  -0.945418 -1.394249     1.250409
326336 -0.442269 -1.045417 -0.895658   0.144437 -1.289604    -0.915445
326337 -0.419946 -1.637762 -1.568616  -0.486532 -1.758268    -0.543270
326338 -0.180761 -1.170073 -1.000187   0.817122 -1.222525     2.005098
326339 -0.442269 -1.837031 -1.669689  -0.074577 -2.116026     1.436497

[326340 rows x 6 columns]

In [43]:
x_test = df_test[['PRECTOT','T2M','T2M_MAX','T2M_RANGE','TS','WS10M_RANGE']]

In [44]:
from sklearn.neural_network import MLPClassifier
import numpy as np

y_train_2 = y_train.values.ravel()
y_train_2 =y_train_2.astype('int')
y_train_2

array([1, 2, 2, ..., 0, 0, 0])

In [45]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(x_train, y_train_2)
y_pred = clf.predict(x_test)

In [46]:
y_pred = pd.DataFrame(y_pred)
y_pred.columns = ['score']

In [47]:
from sklearn.metrics import accuracy_score
y_test =y_test.astype('int')
print(accuracy_score(y_test, y_pred))

0.812012012012012

In [48]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred, labels=[1,2], average='micro')
precision = precision_score(y_test, y_pred, labels=[1,2], average='micro')
recall

0.009014634146341464

In [49]:
precision

0.2079207920792079

In [50]:
x_train = df5[['T2M_RANGE','T2M_MAX','TS','T2M','WS10M_RANGE']]
y_train = df5[['score']]

In [51]:
df_test = pd.read_csv('test_timeseries.csv')
df_test = df_test.dropna()

scaler = StandardScaler()
y_test = df_test[['score']]
df_test = df_test[['T2M_RANGE','T2M_MAX','TS','T2M','WS10M_RANGE']]
scaler.fit(df_test)

df_test = scaler.transform(df_test)


df_test = pd.DataFrame(df_test)
df_test.columns = ['T2M_RANGE','T2M_MAX','TS','T2M','WS10M_RANGE']
df_test

        T2M_RANGE   T2M_MAX        TS       T2M  WS10M_RANGE
0       -1.130537 -0.092256  0.159317  0.172940    -1.318635
1       -0.030253  0.137535  0.018002  0.030995    -0.796556
2       -0.629934 -0.781627 -0.799475 -0.809753    -1.148054
3        0.851017 -0.519873 -0.605392 -0.616854    -0.615637
4        0.449492 -0.960449 -0.954206 -0.962616    -0.233123
...           ...       ...       ...       ...          ...
326335  -0.945418 -1.560841 -1.394249 -1.385720     1.250409
326336   0.144437 -0.895658 -1.289604 -1.045417    -0.915445
326337  -0.486532 -1.568616 -1.758268 -1.637762    -0.543270
326338   0.817122 -1.000187 -1.222525 -1.170073     2.005098
326339  -0.074577 -1.669689 -2.116026 -1.837031     1.436497

[326340 rows x 5 columns]

In [53]:
x_test = df_test[['T2M_RANGE','T2M_MAX','TS','T2M','WS10M_RANGE']]

In [54]:
from sklearn.neural_network import MLPClassifier
import numpy as np

y_train_2 = y_train.values.ravel()
y_train_2 =y_train_2.astype('int')
y_train_2

array([1, 2, 2, ..., 0, 0, 0])

In [55]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(x_train, y_train_2)
y_pred = clf.predict(x_test)

In [56]:
y_pred = pd.DataFrame(y_pred)
y_pred.columns = ['score']

from sklearn.metrics import accuracy_score
y_test =y_test.astype('int')
print(accuracy_score(y_test, y_pred))

0.8117791260648404

In [57]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred, labels=[1,2], average='micro')
precision = precision_score(y_test, y_pred, labels=[1,2], average='micro')
recall

0.013385365853658536

In [58]:
precision

0.19712643678160918